// ---------------------------------------------------------------------------
// AI Actions & Human Approvals — tab-specific data for AIActionsModule
// ---------------------------------------------------------------------------

import type { AIAction, ApprovalItem } from "./AIActionsModule"

// ─── EXECUTIVE CONTROL TOWER ─────────────────────────────────────────────────

export const ectActions: AIAction[] = [
  {
    id: "ect-ai-1",
    title: "Connected demand risk to allocation exposure",
    segment: "Seasonal / Event",
    sourceTab: "Demand Planning + Inventory",
    sourceTabId: "demand",
    detected: "Under-forecast bias running -8.9% linked to protected allocation need before window",
    actionTaken: "Linked demand risk signal to inventory allocation exposure across both tabs",
    status: "completed",
    drawer: {
      title: "Connected demand risk to allocation exposure",
      status: "completed",
      explanation: "AI detected that the under-forecast bias in Seasonal / Event SKUs is directly tied to under-allocation exposure. By linking the two signals, the AI created a cross-functional view of the revenue risk before the selling window.",
      signals: ["Forecast bias -8.9% vs actual velocity", "Seasonal / Event allocation readiness 72%", "Allocation lock deadline proximity", "214 stores with stockout exposure"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "demand",
      segment: "Seasonal / Event",
      segmentStrategy: "Pre-window push allocation with forecast uplift",
      metrics: [
        { label: "Forecast bias", value: "-8.9% vs actual" },
        { label: "Allocation readiness", value: "72%" },
        { label: "Stores at risk", value: "214" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Cross-linking demand and allocation signals surfaces the full $2.4M revenue exposure in one view.",
      recommendedAction: "Review the demand-allocation link in Demand Planning, then approve forecast uplift and push allocation.",
      guardrailNote: "Signal linkage is autonomous. No allocation or forecast change was made without approval.",
      actionLabel: "Go to Demand Planning",
      actionTabId: "demand",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "ect-ai-2",
    title: "Prioritized network constraints by segment impact",
    segment: "Seasonal / Event + Consistent Replenishment",
    sourceTab: "DC Capacity & Transportation",
    sourceTabId: "dc-capacity",
    detected: "Savannah and Joliet DC pressure affecting priority segment outbound flow",
    actionTaken: "Ranked Savannah and Joliet constraints by store service impact across segments",
    status: "completed",
    drawer: {
      title: "Prioritized network constraints by segment impact",
      status: "completed",
      explanation: "AI identified capacity pressure at Savannah (94%) and Joliet (91%) DCs and ranked these constraints by their impact on Seasonal / Event and Consistent Replenishment store service — surfacing the highest-value bottlenecks first.",
      signals: ["Savannah DC at 94% capacity", "Joliet DC at 91% capacity", "Seasonal / Event segment outbound priority", "Consistent Replenishment replenishment cycle at risk"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }],
      primarySourceTabId: "dc-capacity",
      segment: "Seasonal / Event + Consistent Replenishment",
      segmentStrategy: "Wave re-sequencing to protect priority segment outbound flow",
      metrics: [
        { label: "DCs with pressure", value: "Savannah, Joliet" },
        { label: "Outbound segments at risk", value: "Seasonal / Event, Consistent Replenishment" },
        { label: "Recommendation", value: "Wave re-sequencing" },
      ],
      humanApprovalRequired: false,
      businessImpact: "If not resolved, DC pressure delays on-time store delivery for 214 at-risk stores before the selling window.",
      recommendedAction: "Approve the Savannah outbound wave change and overflow route capacity in DC Capacity.",
      guardrailNote: "Constraint ranking is autonomous. Physical re-sequencing requires DC manager sign-off.",
      actionLabel: "Go to DC Capacity",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "ect-ai-3",
    title: "Flagged store execution dependency for promo push",
    segment: "Promo / Merchant-Driven",
    sourceTab: "Store Execution",
    sourceTabId: "store-execution",
    detected: "Promo display readiness below threshold in subset of stores",
    actionTaken: "Flagged display readiness as allocation dependency before promo push",
    status: "watchlist",
    drawer: {
      title: "Flagged store execution dependency for promo push",
      status: "watchlist",
      explanation: "AI detected that promo display completion is below threshold in a subset of stores, meaning full promo push allocation would arrive before stores are ready to execute — risking backroom overflow and wasted allocation.",
      signals: ["Display readiness below threshold", "Promo / Merchant-Driven segment classification", "Allocation lock approaching", "Store execution capacity constraint"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "store-execution",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Delay full promo push pending display readiness confirmation",
      metrics: [
        { label: "Segment", value: "Promo / Merchant-Driven" },
        { label: "Status", value: "Watchlist — no action taken" },
        { label: "Value at risk", value: "$520K" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Allocating before display readiness degrades promo sell-through and wastes allocation capacity.",
      recommendedAction: "Approve the display-readiness dependency rule to delay promo push for unready stores.",
      guardrailNote: "Watchlist status — flagged but no allocation decision delayed without human approval.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for review",
    },
  },
]

export const ectApprovals: ApprovalItem[] = [
  {
    id: "ect-ap-1",
    title: "Approve Seasonal forecast uplift and protected allocation",
    segment: "Seasonal / Event",
    recommendation: "Increase near-term forecast for selected Seasonal / Event SKU families and lock protected allocation before window",
    whyApproval: "High revenue exposure ahead of short selling window requires executive approval before allocation lock",
    valueAtRisk: "$2.4M",
    owner: "Demand Planning + Allocation",
    status: "pending",
    drawer: {
      title: "Approve Seasonal forecast uplift and protected allocation",
      status: "pending",
      explanation: "AI has recommended a forecast uplift for Seasonal / Event SKUs running 8.9% above baseline, and a protected pre-window push allocation to 214 at-risk stores. Both decisions require planner approval before allocation lock.",
      signals: ["Forecast bias -8.9%", "214 stores with stockout exposure", "Allocation lock approaching", "Revenue at risk: $2.4M"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "demand",
      segment: "Seasonal / Event",
      segmentStrategy: "Forecast uplift + protected pre-window push allocation",
      metrics: [
        { label: "Forecast bias", value: "-8.9%" },
        { label: "Revenue at risk", value: "$2.4M" },
        { label: "Stores affected", value: "214" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Approving unlocks correct allocation and protects up to $2.4M in Seasonal / Event revenue before the selling window closes.",
      recommendedAction: "Approve forecast uplift and protected allocation in Demand Planning.",
      guardrailNote: "AI will not commit inventory without explicit planner sign-off.",
      actionLabel: "Go to Demand Planning",
      actionTabId: "demand",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "ect-ap-2",
    title: "Approve inbound recovery for constrained SKUs",
    segment: "Constrained / Exception",
    recommendation: "Expedite delayed inbound PO and approve substitute SKUs where supplier fill-rate is short",
    whyApproval: "Inbound recovery tradeoffs and substitution decisions affect merchandising and allocation across stores",
    valueAtRisk: "$1.1M",
    owner: "Supplier Management + Inventory Planning",
    status: "needs-approval",
    drawer: {
      title: "Approve inbound recovery for constrained SKUs",
      status: "needs-approval",
      explanation: "AI has flagged 43 at-risk POs and fill-rate variance on Constrained / Exception SKUs. Recovery options include expedite and substitution — both require cross-functional approval due to cost and merchandising implications.",
      signals: ["43 at-risk POs", "Supplier fill-rate variance on priority SKUs", "Constrained / Exception segment flag", "Allocation lock approaching"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Constrained / Exception",
      segmentStrategy: "Human-reviewed fallback allocation with expedite or substitution",
      metrics: [
        { label: "At-risk POs", value: "43" },
        { label: "Revenue at risk", value: "$1.1M" },
        { label: "Recovery options", value: "Expedite + substitution" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Without recovery approval, constrained SKUs will result in partial allocation and lost revenue across affected stores.",
      recommendedAction: "Review PO risk in Supplier & Inbound Flow and approve substitute recovery or expedite.",
      guardrailNote: "No substitution or expedite action is taken without human approval.",
      actionLabel: "Go to Supplier & Inbound",
      actionTabId: "supplier-inbound",
      secondaryLabel: "Mark for review",
    },
  },
]

// ─── DEMAND PLANNING ─────────────────────────────────────────────────────────

export const demandActions: AIAction[] = [
  {
    id: "dp-ai-1",
    title: "Detected forecast bias by SKU segment",
    segment: "Seasonal / Event",
    sourceTab: "Demand Planning",
    sourceTabId: "demand",
    detected: "Forecast bias running -8.9% against actual velocity for Seasonal / Event SKUs",
    actionTaken: "Created uplift recommendation and linked it to revenue-at-risk calculation",
    status: "completed",
    drawer: {
      title: "Detected forecast bias by SKU segment",
      status: "completed",
      explanation: "AI detected that Seasonal / Event SKUs are running 8.9% above the baseline forecast. This under-forecast bias threatens allocation accuracy before the selling window and has been quantified as $2.4M in revenue exposure.",
      signals: ["Velocity delta +8.9% vs baseline forecast", "Seasonal / Event segment classification", "Allocation lock deadline proximity", "Historical seasonal bias pattern"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }],
      primarySourceTabId: "demand",
      segment: "Seasonal / Event",
      segmentStrategy: "Forecast uplift + protected pre-window push allocation",
      metrics: [
        { label: "Forecast bias", value: "-8.9% vs actual velocity" },
        { label: "Revenue at risk", value: "$2.4M" },
        { label: "Recommendation", value: "Forecast uplift + allocation push" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Under-forecast bias leads to under-allocation to high-velocity stores ahead of the selling window, causing lost sales.",
      recommendedAction: "Approve the forecast uplift in the Human Approval section below.",
      guardrailNote: "Bias detection is autonomous. Uplift requires planner approval before allocation lock.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dp-ai-2",
    title: "Separated stable from event-driven forecast logic",
    segment: "Consistent Replenishment + Seasonal / Event",
    sourceTab: "Demand Planning",
    sourceTabId: "demand",
    detected: "Stable SKUs require baseline replenishment; Seasonal SKUs require time-bound push logic",
    actionTaken: "Applied differentiated forecast treatment by segment",
    status: "completed",
    drawer: {
      title: "Separated stable from event-driven forecast logic",
      status: "completed",
      explanation: "AI identified that applying a single forecast model to both Consistent Replenishment and Seasonal / Event SKUs creates systematic error. Differentiated treatment was applied within planning guardrails.",
      signals: ["Segment classification from AI-Driven SKU Segmentation", "Forecast error rate differential by segment", "Selling window signal for Seasonal / Event", "Replenishment cycle signal for Consistent Replenishment"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "AI-Driven SKU Segmentation", id: "sku-segmentation" }],
      primarySourceTabId: "demand",
      segment: "Consistent Replenishment + Seasonal / Event",
      segmentStrategy: "Differentiated forecast logic by segment type",
      metrics: [
        { label: "Segments with differentiated logic", value: "2" },
        { label: "Forecast model", value: "Segment-specific applied" },
        { label: "Human approval required", value: "No" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Differentiated logic improves forecast accuracy for both segments and prevents under- or over-allocation.",
      recommendedAction: "No action required. Confirm differentiated forecast logic is reflected in planning outputs.",
      guardrailNote: "Differentiated treatment is within autonomous planning guardrails — no forecast or inventory commitment was made.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dp-ai-3",
    title: "Flagged low-confidence demand signals",
    segment: "Treasure Hunt / Limited Buy",
    sourceTab: "Demand Planning",
    sourceTabId: "demand",
    detected: "Sparse SKU history but similar-item analogs available",
    actionTaken: "Routed forecast logic to analog-based estimate pending planner review",
    status: "watchlist",
    drawer: {
      title: "Flagged low-confidence demand signals for limited-buy SKUs",
      status: "watchlist",
      explanation: "AI detected sparse demand history for Treasure Hunt / Limited Buy SKUs and identified similar-item analogs that can serve as a forecast basis. Analog-based forecasting was recommended and routed for approval due to markdown risk.",
      signals: ["Sparse SKU demand history", "Similar-item analog available", "Treasure Hunt / Limited Buy segment classification", "Markdown risk if over-forecasted"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }],
      primarySourceTabId: "demand",
      segment: "Treasure Hunt / Limited Buy",
      segmentStrategy: "Analog-based forecast pending human approval",
      metrics: [
        { label: "History depth", value: "Sparse" },
        { label: "Analog signal", value: "Available" },
        { label: "Value at risk", value: "$640K" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Without an approved forecast basis, these SKUs will be under-planned or over-planned, risking stockout or markdown.",
      recommendedAction: "Approve the analog-based forecast method below.",
      guardrailNote: "Watchlist — no forecast was committed. Analog method requires planner approval.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
]

export const demandApprovals: ApprovalItem[] = [
  {
    id: "dp-ap-1",
    title: "Approve Seasonal / Event forecast uplift",
    segment: "Seasonal / Event",
    recommendation: "Apply temporary +12% uplift for selected Southeast Seasonal / Event SKU families to correct -8.9% under-forecast bias",
    whyApproval: "High revenue exposure before short selling window requires planner sign-off",
    valueAtRisk: "$2.4M",
    owner: "Demand Planning",
    status: "pending",
    drawer: {
      title: "Approve Seasonal / Event forecast uplift",
      status: "pending",
      explanation: "Actual velocity and promotion lift are exceeding baseline demand assumptions for Southeast Seasonal / Event SKUs. AI has created an uplift recommendation. Human approval is required before any forecast or inventory commitment is made.",
      signals: ["Velocity delta +8.9% vs baseline", "Seasonal / Event segment", "Allocation lock approaching", "$2.4M revenue at risk", "38 stores exposed"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "demand",
      segment: "Seasonal / Event",
      segmentStrategy: "Forecast uplift before allocation lock",
      metrics: [
        { label: "Bias",            value: "-8.9% vs actual velocity" },
        { label: "Value at risk",   value: "$2.4M" },
        { label: "Stores at risk",  value: "38" },
        { label: "Uplift proposed", value: "+12% for selected Southeast stores" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$2.4M of revenue exposure and 38 stores at risk if uplift is not approved before forecast lock. Allocation may under-support high-velocity stores during the selling window.",
      recommendedAction: "Approve temporary +12% uplift and send to Inventory & Allocation for protected push allocation.",
      guardrailNote: "AI will not commit any forecast or allocation change without explicit planner approval.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dp-ap-2",
    title: "Approve Consistent Replenishment baseline adjustment",
    segment: "Consistent Replenishment",
    recommendation: "Increase 4-week baseline forecast by +6% for selected Midwest paper goods",
    whyApproval: "Impacts replenishment quantities and DC flow — requires planner and supply planning sign-off",
    valueAtRisk: "$1.7M",
    owner: "Demand Planning + Supply Planning",
    status: "pending",
    drawer: {
      title: "Approve Consistent Replenishment baseline adjustment",
      status: "pending",
      explanation: "Recent velocity acceleration suggests the baseline demand forecast is understated for selected Midwest paper goods. A +6% 4-week adjustment is recommended. This approval impacts replenishment quantities and DC flow.",
      signals: ["Velocity acceleration detected in Midwest pantry SKUs", "Bias: -6.7% vs actual", "27 stores with near-term gap", "DC flow timing dependency"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "DC Capacity & Transportation", id: "dc-capacity" }],
      primarySourceTabId: "demand",
      segment: "Consistent Replenishment",
      segmentStrategy: "Baseline correction + replenishment quantity adjustment",
      metrics: [
        { label: "Bias",              value: "-6.7% vs actual" },
        { label: "Value at risk",     value: "$1.7M" },
        { label: "Stores at risk",    value: "27" },
        { label: "Adjustment",        value: "+6% 4-week baseline" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$1.7M revenue exposure and 27 stores at risk. Replenishment quantities may remain below near-term demand if the baseline is not adjusted.",
      recommendedAction: "Approve +6% 4-week baseline adjustment and notify Supply Planning.",
      guardrailNote: "No replenishment quantity or DC flow change has been committed without approval.",
      actionLabel: "Go to DC Capacity & Transportation",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dp-ap-3",
    title: "Validate Promo / Merchant-Driven lift assumptions",
    segment: "Promo / Merchant-Driven",
    recommendation: "Confirm Party promo timing and expected lift before the next forecast lock",
    whyApproval: "Merchant calendar confirmation required before forecast can be locked",
    valueAtRisk: "$860K",
    owner: "Merchandising + Demand Planning",
    status: "needs-approval",
    drawer: {
      title: "Validate Promo / Merchant-Driven lift assumptions",
      status: "needs-approval",
      explanation: "Party endcap promotion timing shifted relative to the prior planning cycle. The current forecast may not reflect actual promo pull-through. Merchant confirmation is required before forecast lock.",
      signals: ["Circular timing shifted from prior cycle", "Promo lift assumption unvalidated", "14 stores with forecast uncertainty", "Forecast lock approaching"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "demand",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Promo lift validation before forecast lock",
      metrics: [
        { label: "Bias",             value: "-5.2% vs baseline" },
        { label: "Value at risk",    value: "$860K" },
        { label: "Stores at risk",   value: "14" },
        { label: "Merchant sign-off", value: "Required" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$860K revenue exposure and 14 stores at risk. Forecast may not reflect promo lift, and stores may receive insufficient product for display execution.",
      recommendedAction: "Request merchant validation before forecast lock.",
      guardrailNote: "No forecast or allocation action taken until merchant confirms promo timing and lift assumptions.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for review",
    },
  },
]

// ─── INVENTORY & ALLOCATION ────────────────────────────────────────────────────

export const inventoryActions: AIAction[] = [
  {
    id: "inv-ai-1",
    title: "Ranked stores by absorption capacity",
    segment: "Seasonal / Event",
    sourceTab: "Inventory & Allocation",
    sourceTabId: "inventory",
    detected: "High-velocity stores can absorb larger pre-window push; lower-velocity stores risk backroom overflow",
    actionTaken: "Ranked store clusters by absorption capacity and service risk for Seasonal / Event allocation",
    status: "completed",
    drawer: {
      title: "Ranked stores by absorption capacity",
      status: "completed",
      explanation: "AI identified 214 stores with stockout exposure and ranked them by absorption capacity to ensure the Seasonal / Event push prioritizes the highest-risk stores. Store clusters with backroom overflow risk were identified and excluded from the push tier to prevent waste.",
      signals: ["214 stores at stockout risk", "Store absorption capacity scored by DC catchment", "Backroom overflow risk flagged at 42 lower-velocity stores", "Seasonal / Event segment classification"],
      sourceTabs: [{ label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "inventory",
      segment: "Seasonal / Event",
      segmentStrategy: "Tiered push by absorption rank — high-velocity stores first",
      metrics: [
        { label: "Stores ranked",      value: "214 at-risk" },
        { label: "High absorption",    value: "Tier 1 push candidates" },
        { label: "Timestamp",          value: "Today · 8:18 AM" },
        { label: "Human approval",     value: "Required before push release" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Proper store ranking ensures available inventory flows to highest-risk stores. Without ranking, even inventory and backroom overflow would reduce effective service.",
      recommendedAction: "Approve the Seasonal / Event push allocation in the Human Approval column.",
      guardrailNote: "Store ranking is autonomous within guardrails. Final push allocation release requires planner approval.",
    },
  },
  {
    id: "inv-ai-2",
    title: "Protected baseline replenishment volume",
    segment: "Consistent Replenishment",
    sourceTab: "Inventory & Allocation",
    sourceTabId: "inventory",
    detected: "Everyday SKUs need steady flow to prevent service degradation at high-velocity stores",
    actionTaken: "Protected replenishment volume for high-velocity stores within planning guardrails",
    status: "completed",
    drawer: {
      title: "Protected baseline replenishment volume",
      status: "completed",
      explanation: "AI identified that Consistent Replenishment SKUs were at risk of losing allocation volume to the Seasonal / Event push. Baseline replenishment volume was autonomously protected within planning guardrails to prevent service degradation at high-velocity Midwest stores.",
      signals: ["Consistent Replenishment segment at risk of allocation crowding", "High-velocity Midwest stores below coverage", "Baseline volume protection applied within guardrails", "No inventory committed — protection flag only"],
      sourceTabs: [{ label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "inventory",
      segment: "Consistent Replenishment",
      segmentStrategy: "Protected baseline replenishment before seasonal push competes for volume",
      metrics: [
        { label: "Protection applied",  value: "Consistent Replenishment volume" },
        { label: "Timestamp",           value: "Today · 8:21 AM" },
        { label: "Human approval",      value: "Not required for protection flag" },
        { label: "Next step",           value: "Confirm in final allocation plan" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Without protection, Consistent Replenishment SKUs would have lost allocation to the Seasonal / Event push, degrading everyday service levels at high-velocity stores.",
      recommendedAction: "Confirm replenishment protection is reflected in the final allocation plan before lock.",
      guardrailNote: "Protection is autonomous and within guardrails. No inventory committed without human approval.",
    },
  },
  {
    id: "inv-ai-3",
    title: "Flagged constrained allocation fallback scenario",
    segment: "Constrained / Exception",
    sourceTab: "Inventory & Allocation",
    sourceTabId: "inventory",
    detected: "Recommended allocation exceeds available executable supply for constrained SKUs",
    actionTaken: "Created fallback allocation scenario for planner review",
    status: "watchlist",
    drawer: {
      title: "Flagged constrained allocation fallback scenario",
      status: "watchlist",
      explanation: "AI detected that the recommended allocation for Constrained / Exception SKUs exceeds available executable supply, likely due to supplier fill-rate variance. A fallback allocation scenario with partial fulfillment and substitution options was created but not committed — requires planner review before any allocation action.",
      signals: ["Recommended allocation exceeds executable supply", "Supplier fill-rate variance detected", "Constrained / Exception segment", "Fallback scenario created — not committed"],
      sourceTabs: [{ label: "Inventory & Allocation", id: "inventory" }, { label: "Supplier & Inbound Flow", id: "supplier-inbound" }],
      primarySourceTabId: "inventory",
      segment: "Constrained / Exception",
      segmentStrategy: "Human-reviewed fallback with partial allocation and substitution",
      metrics: [
        { label: "Supply gap",       value: "Exceeds executable supply" },
        { label: "Value at risk",    value: "$1.1M" },
        { label: "Timestamp",        value: "Today · 8:25 AM" },
        { label: "Fallback status",  value: "Created — not committed" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Without an approved fallback, constrained SKUs will result in partial and inconsistent allocation across stores with no visibility into priority.",
      recommendedAction: "Approve the constrained fallback allocation scenario in the Human Approval column.",
      guardrailNote: "Watchlist — fallback created but no allocation committed without explicit planner approval.",
      actionLabel: "Go to Supplier & Inbound Flow",
      actionTabId: "supplier-inbound",
    },
  },
]

export const inventoryApprovals: ApprovalItem[] = [
  {
    id: "inv-ap-1",
    title: "Approve Seasonal / Event protected push allocation",
    segment: "Seasonal / Event",
    recommendation: "Reserve $3.6M of available Seasonal / Event inventory for 72 high-risk Southeast stores",
    whyApproval: "High service exposure and constrained inventory require planner decision on store prioritization",
    valueAtRisk: "$2.8M",
    owner: "Allocation Planning",
    status: "pending",
    drawer: {
      title: "Approve Seasonal / Event protected push allocation",
      status: "pending",
      explanation: "Demand Planning identified a Seasonal / Event under-forecast in the Southeast, while Savannah DC has limited available inventory. AI has ranked 72 high-risk stores by absorption capacity and recommends protecting inventory for those stores before allocation lock. Approval required before any inventory is committed.",
      signals: ["72 stores ranked by absorption capacity", "Savannah DC constrained", "$3.6M shortage vs target", "Allocation lock: Jun 10", "$2.8M service risk"],
      sourceTabs: [
        { label: "Demand Planning", id: "demand" },
        { label: "DC Capacity & Transportation", id: "dc-capacity" },
        { label: "Store Execution", id: "store-execution" },
      ],
      primarySourceTabId: "inventory",
      segment: "Seasonal / Event",
      segmentStrategy: "Protected pre-window push to high-absorption stores",
      metrics: [
        { label: "Stores at risk",    value: "72" },
        { label: "Inventory short",   value: "$3.6M vs target" },
        { label: "Value at risk",     value: "$2.8M service risk" },
        { label: "Allocation lock",   value: "Jun 10" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$2.8M service risk and 72 stores exposed if protected allocation is not approved before the Jun 10 allocation lock. High-velocity stores may not receive enough inventory during the seasonal selling window.",
      recommendedAction: "Approve protected push allocation and send priority flow to DC Capacity & Transportation.",
      guardrailNote: "No inventory committed without explicit planner approval.",
      actionLabel: "Go to DC Capacity & Transportation",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "inv-ap-2",
    title: "Approve constrained fallback allocation",
    segment: "Constrained / Exception",
    recommendation: "Partially allocate supplier-limited cleaning SKUs and substitute where possible",
    whyApproval: "Tradeoff across stores and SKU families requires planner decision; not safe to fully automate",
    valueAtRisk: "$1.1M",
    owner: "Inventory Planning",
    status: "needs-approval",
    drawer: {
      title: "Approve constrained fallback allocation",
      status: "needs-approval",
      explanation: "Supplier and inventory constraints prevent the full recommended allocation for Constrained / Exception SKUs from being executed. AI created a fallback scenario with partial allocation and substitution options. The tradeoff across stores and SKU families is not safely automatable — requires planner decision.",
      signals: ["Full allocation not executable", "Supplier fill-rate short on priority SKUs", "Partial allocation scenario created", "$1.1M value at risk"],
      sourceTabs: [
        { label: "Inventory & Allocation", id: "inventory" },
        { label: "Supplier & Inbound Flow", id: "supplier-inbound" },
      ],
      primarySourceTabId: "inventory",
      segment: "Constrained / Exception",
      segmentStrategy: "Partial allocation + SKU substitution where available",
      metrics: [
        { label: "Value at risk",     value: "$1.1M" },
        { label: "Recovery options",  value: "Partial + substitution" },
        { label: "Stores affected",   value: "Constrained SKU families" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$1.1M exposure tied to constrained cleaning SKUs. Inventory may be spread too thinly or sent to lower-priority stores without approved guidance.",
      recommendedAction: "Approve partial allocation and substitution logic.",
      guardrailNote: "No substitution or partial allocation committed without explicit approval.",
      actionLabel: "Go to Supplier & Inbound Flow",
      actionTabId: "supplier-inbound",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "inv-ap-3",
    title: "Approve Treasure Hunt controlled transfer",
    segment: "Treasure Hunt / Limited Buy",
    recommendation: "Transfer $1.4M of limited-buy home goods from Marietta DC to the Southeast demand pool",
    whyApproval: "Sparse SKU history, markdown risk, trailer availability, and receiving capacity require planner sign-off",
    valueAtRisk: "$720K",
    owner: "Inventory Planning + Transportation",
    status: "pending",
    drawer: {
      title: "Approve Treasure Hunt controlled transfer",
      status: "pending",
      explanation: "Limited-buy home goods are above target in Southwest while Southeast has stronger absorption potential. AI recommends transferring $1.4M of excess inventory from Marietta DC to the Southeast demand pool. Transfer affects DC capacity and transportation schedule — requires planner approval.",
      signals: ["$4.2M above target at Marietta DC", "Southeast absorption pool has capacity", "Transfer route: Marietta → Savannah DC", "Trailer availability and receiving capacity dependency"],
      sourceTabs: [
        { label: "DC Capacity & Transportation", id: "dc-capacity" },
      ],
      primarySourceTabId: "inventory",
      segment: "Treasure Hunt / Limited Buy",
      segmentStrategy: "Controlled transfer from overstock to high-absorption demand region",
      metrics: [
        { label: "Transfer amount",   value: "$1.4M" },
        { label: "Overstock pool",    value: "$4.2M at Marietta DC" },
        { label: "Carrying risk",     value: "$720K if not transferred" },
        { label: "Transfer route",    value: "Marietta → Savannah DC" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$720K carrying risk and markdown exposure if excess inventory remains in the Southwest. Higher-absorption stores in Southeast remain under-supported.",
      recommendedAction: "Approve transfer subject to transportation and receiving capacity.",
      guardrailNote: "No transfer committed without explicit approval. Transportation and DC schedule must be confirmed.",
      actionLabel: "Go to DC Capacity & Transportation",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for Review",
    },
  },
]

// ─── SUPPLIER & INBOUND FLOW ───────────────────────────────────────────────────

export const supplierActions: AIAction[] = [
  {
    id: "si-ai-1",
    title: "Linked PO risk to SKU segment impact",
    segment: "Constrained / Exception",
    sourceTab: "Supplier & Inbound Flow",
    sourceTabId: "supplier-inbound",
    detected: "Supplier fill-rate variance across 43 at-risk POs affecting priority SKU families",
    actionTaken: "Connected at-risk POs to allocation and revenue exposure across planning modules",
    status: "completed",
    drawer: {
      title: "Linked PO risk to SKU segment impact",
      status: "completed",
      explanation: "AI identified 43 at-risk POs with fill-rate variance affecting priority SKU families and connected these inbound constraints to active allocation decisions — surfacing the full downstream impact across planning modules.",
      signals: ["43 at-risk POs identified", "Supplier fill-rate variance on priority SKUs", "Constrained / Exception segment", "Cross-module allocation linkage applied", "Autonomous within guardrails — no PO or allocation committed"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Constrained / Exception",
      segmentStrategy: "Signal linking across supplier risk and allocation exposure",
      metrics: [
        { label: "At-risk POs linked",        value: "43" },
        { label: "Allocation modules linked",  value: "Inventory & Allocation" },
        { label: "Revenue exposure surfaced",  value: "$1.1M+" },
        { label: "Timestamp",                 value: "Today · 8:24 AM" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Linking PO risk to allocation decisions surfaces downstream exposure that would otherwise be invisible at planning review, enabling faster recovery prioritization.",
      recommendedAction: "Review constrained PO approvals in the Human Approval column.",
      guardrailNote: "Signal linking is autonomous within guardrails. No PO or allocation commitment was made.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "si-ai-2",
    title: "Flagged inbound timing risk for Seasonal / Event SKUs",
    segment: "Seasonal / Event",
    sourceTab: "Supplier & Inbound Flow",
    sourceTabId: "supplier-inbound",
    detected: "Inbound ETA variance on Savannah DC seasonal PO may miss selling window",
    actionTaken: "Recommended expedite review for critical Seasonal / Event inbound PO",
    status: "watchlist",
    drawer: {
      title: "Flagged inbound timing risk for Seasonal / Event SKUs",
      status: "watchlist",
      explanation: "AI detected ETA variance on GreenLeaf Seasonal Imports PO-78421 destined for Savannah DC. If the 7-day slip persists, the inventory may arrive after the allocation window closes, negating the protected push allocation strategy for Southeast stores.",
      signals: ["PO-78421 ETA slipped 7 days", "Seasonal / Event segment at risk", "Allocation window: Jun 10", "42 Southeast stores exposed", "Expedite cost tradeoff unresolved"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Seasonal / Event",
      segmentStrategy: "Expedite review to protect selling window and allocation",
      metrics: [
        { label: "PO at risk",       value: "GreenLeaf · PO-78421" },
        { label: "ETA slip",         value: "+7 days" },
        { label: "Value at risk",    value: "$1.6M" },
        { label: "Stores exposed",   value: "42" },
        { label: "Timestamp",        value: "Today · 8:27 AM" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$1.6M in Seasonal / Event revenue at risk if inventory misses the Southeast allocation window.",
      recommendedAction: "Approve expedite for PO-78421 or choose substitute recovery before the Jun 10 allocation lock.",
      guardrailNote: "Watchlist — ETA risk flagged and expedite path identified. No expedite committed without management approval.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "si-ai-3",
    title: "Identified supplier risk for baseline replenishment",
    segment: "Consistent Replenishment",
    sourceTab: "Supplier & Inbound Flow",
    sourceTabId: "supplier-inbound",
    detected: "Short shipment on everyday SKU PO threatens steady replenishment flow",
    actionTaken: "Prioritized recovery by store service impact and surfaced for planner review",
    status: "completed",
    drawer: {
      title: "Identified supplier risk for baseline replenishment",
      status: "completed",
      explanation: "AI detected that ValuePack Consumables Co. PO-78104 shipped at 82% fill versus 96% expected, reducing available inventory for Midwest Consistent Replenishment SKUs. Recovery was prioritized by store service impact and surfaced for planner review.",
      signals: ["ValuePack PO-78104: 82% fill vs 96% expected", "Consistent Replenishment segment", "31 Midwest stores exposed", "Recovery ranked by store service impact", "No substitute committed without approval"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Consistent Replenishment",
      segmentStrategy: "Service-impact-ranked recovery for baseline replenishment SKUs",
      metrics: [
        { label: "Supplier / PO",     value: "ValuePack · PO-78104" },
        { label: "Fill-rate received", value: "82% vs 96% expected" },
        { label: "Value at risk",     value: "$1.1M" },
        { label: "Stores exposed",    value: "31" },
        { label: "Timestamp",         value: "Today · 8:31 AM" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Short shipment on everyday SKUs creates service gaps at high-velocity Midwest stores if not recovered before next replenishment cycle.",
      recommendedAction: "Approve substitute recovery or prioritize available inbound supply for high-velocity stores.",
      guardrailNote: "Service-impact ranking is autonomous. Recovery action and substitution require planner and supplier confirmation.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for Review",
    },
  },
]

export const supplierApprovals: ApprovalItem[] = [
  {
    id: "si-ap-1",
    title: "Approve expedite for Seasonal / Event inbound PO",
    segment: "Seasonal / Event",
    recommendation: "Expedite delayed GreenLeaf Seasonal Imports PO-78421 into Savannah DC",
    whyApproval: "Operating cost tradeoff on expedite requires management approval",
    valueAtRisk: "$1.6M",
    owner: "Supplier Management + Inbound Planning",
    status: "pending",
    drawer: {
      title: "Approve expedite for Seasonal / Event inbound PO",
      status: "pending",
      explanation: "GreenLeaf Seasonal Imports PO-78421 slipped by 7 days and may miss the Southeast Seasonal / Event allocation window. Expedite is recommended to protect $1.6M in seasonal revenue and 42 store deployments. Approval required due to operating cost tradeoff.",
      signals: ["PO-78421 ETA slipped 7 days", "Savannah DC receiving window at risk", "42 Southeast stores exposed", "$1.6M at risk", "Expedite cost: management decision required"],
      sourceTabs: [
        { label: "Supplier & Inbound Flow", id: "supplier-inbound" },
        { label: "Demand Planning", id: "demand" },
        { label: "DC Capacity & Transportation", id: "dc-capacity" },
      ],
      primarySourceTabId: "supplier-inbound",
      segment: "Seasonal / Event",
      segmentStrategy: "Expedite to protect selling window and allocation",
      metrics: [
        { label: "Supplier / PO",      value: "GreenLeaf · PO-78421" },
        { label: "ETA slip",           value: "+7 days" },
        { label: "Value at risk",      value: "$1.6M" },
        { label: "Stores exposed",     value: "42" },
        { label: "Allocation lock",    value: "Jun 10" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$1.6M inbound value at risk and 42 stores exposed if the PO does not arrive before allocation release.",
      recommendedAction: "Approve expedite or choose substitute recovery before the Jun 10 allocation lock.",
      guardrailNote: "No expedite action taken without cost and operational sign-off.",
      actionLabel: "Go to DC Capacity & Transportation",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "si-ap-2",
    title: "Approve substitute recovery for Consistent Replenishment short shipment",
    segment: "Consistent Replenishment",
    recommendation: "Use substitute supply or alternate supplier recovery to cover ValuePack short shipment",
    whyApproval: "Substitution affects service, supplier commitment, and allocation decisions",
    valueAtRisk: "$1.1M",
    owner: "Supplier Management + Inventory Planning",
    status: "needs-approval",
    drawer: {
      title: "Approve substitute recovery for Consistent Replenishment short shipment",
      status: "needs-approval",
      explanation: "ValuePack PO-78104 shipped at 82% fill versus 96% expected, reducing available inventory for Midwest replenishment. Substitute recovery is recommended to cover the gap. Substitution affects service levels, supplier commitments, and allocation decisions — requiring cross-functional approval.",
      signals: ["PO-78104: 82% fill vs 96% expected", "31 Midwest stores exposed", "$1.1M value at risk", "Substitute candidates identified", "Supplier commitment impact unresolved"],
      sourceTabs: [
        { label: "Supplier & Inbound Flow", id: "supplier-inbound" },
        { label: "Inventory & Allocation", id: "inventory" },
      ],
      primarySourceTabId: "supplier-inbound",
      segment: "Consistent Replenishment",
      segmentStrategy: "Substitute recovery ranked by store service impact",
      metrics: [
        { label: "Supplier / PO",       value: "ValuePack · PO-78104" },
        { label: "Fill received",       value: "82% vs 96%" },
        { label: "Value at risk",       value: "$1.1M" },
        { label: "Stores exposed",      value: "31" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$1.1M value at risk and 31 stores exposed. Everyday replenishment may remain below service thresholds without approved recovery.",
      recommendedAction: "Approve substitute recovery or prioritize available inbound supply for high-velocity stores.",
      guardrailNote: "No substitution or allocation commitment made without explicit approval.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "si-ap-3",
    title: "Confirm Promo / Merchant-Driven receipt timing",
    segment: "Promo / Merchant-Driven",
    recommendation: "Confirm Party endcap receipt timing before promo allocation is released",
    whyApproval: "Merchant calendar and display timing require cross-functional confirmation",
    valueAtRisk: "$860K",
    owner: "Merchandising + Inbound Planning",
    status: "pending",
    drawer: {
      title: "Confirm Promo / Merchant-Driven receipt timing",
      status: "pending",
      explanation: "BrightParty Goods PO-77988 receipt timing is uncertain after the promo calendar timing shifted. Promo allocation should not be released until inbound timing and display readiness are confirmed by merchant and inbound teams.",
      signals: ["BrightParty PO-77988 receipt date uncertain", "Promo calendar shifted from prior cycle", "14 stores exposed", "$860K value at risk", "Merchant calendar not yet confirmed"],
      sourceTabs: [
        { label: "Supplier & Inbound Flow", id: "supplier-inbound" },
        { label: "Demand Planning", id: "demand" },
        { label: "Store Execution", id: "store-execution" },
      ],
      primarySourceTabId: "supplier-inbound",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Promo receipt timing confirmation before allocation release",
      metrics: [
        { label: "Supplier / PO",      value: "BrightParty · PO-77988" },
        { label: "Issue",              value: "Receipt date uncertain" },
        { label: "Value at risk",      value: "$860K" },
        { label: "Stores exposed",     value: "14" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$860K value at risk and 14 stores exposed. Promo allocation may release before inbound timing and display readiness are confirmed.",
      recommendedAction: "Request merchant and inbound confirmation before allocation release.",
      guardrailNote: "No promo allocation committed until merchant confirms timing and receipt readiness.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for Review",
    },
  },
]

// ─── DC CAPACITY & TRANSPORTATION ────────────────────────────────────────────

export const dcActions: AIAction[] = [
  {
    id: "dc-ai-1",
    title: "Prioritized outbound waves by SKU segment",
    segment: "Seasonal / Event",
    sourceTab: "DC Capacity & Transportation",
    sourceTabId: "dc-capacity",
    detected: "Savannah DC shipping pressure delaying priority Seasonal / Event outbound shipments",
    actionTaken: "Recommended wave re-sequencing for high-risk Seasonal / Event store shipments",
    status: "completed",
    drawer: {
      title: "Prioritized outbound waves by SKU segment",
      status: "completed",
      explanation: "AI detected that Savannah DC is operating at 96% capacity with 22.4 hrs of trailer dwell, causing shipping dock pressure that threatens on-time delivery for Seasonal / Event stores. Wave re-sequencing was recommended to move high-risk Southeast stores earlier in the outbound plan.",
      signals: ["Savannah DC 96% capacity", "22.4 hrs trailer dwell", "Seasonal / Event outbound priority", "72 Southeast stores at risk", "Selling window: Jun 10"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }, { label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "dc-capacity",
      segment: "Seasonal / Event",
      segmentStrategy: "Wave re-sequencing by segment and store risk priority",
      metrics: [
        { label: "DC",               value: "Savannah DC · 96% capacity" },
        { label: "Trailer dwell",    value: "22.4 hrs (target 12 hrs)" },
        { label: "Stores at risk",   value: "72 Southeast stores" },
        { label: "Value at risk",    value: "$1.2M" },
        { label: "Timestamp",        value: "Today · 8:29 AM" },
      ],
      humanApprovalRequired: true,
      businessImpact: "72 Southeast stores may miss priority Seasonal / Event delivery windows if outbound waves are not re-sequenced before the allocation lock.",
      recommendedAction: "Approve the Savannah outbound wave change in the Human Approval column.",
      guardrailNote: "Wave re-sequencing recommendation is within planning guardrails. Physical execution requires DC operations sign-off.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "dc-ai-2",
    title: "Protected baseline replenishment flow at Joliet DC",
    segment: "Consistent Replenishment",
    sourceTab: "DC Capacity & Transportation",
    sourceTabId: "dc-capacity",
    detected: "Joliet pick-wave backlog affecting everyday SKU replenishment cycle",
    actionTaken: "Prioritized Consistent Replenishment picks within Joliet wave sequencing",
    status: "completed",
    drawer: {
      title: "Protected baseline replenishment flow at Joliet DC",
      status: "completed",
      explanation: "AI detected that Joliet DC is at 93% capacity with a pick-wave backlog limiting Consistent Replenishment flow to high-velocity Midwest stores. Replenishment picks were prioritized within current wave sequencing — no additional labor or overtime was requested.",
      signals: ["Joliet DC 93% capacity", "19.1 hrs trailer dwell", "Pick-wave backlog identified", "58 Midwest stores with replenishment exposure", "Consistent Replenishment segment"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "dc-capacity",
      segment: "Consistent Replenishment",
      segmentStrategy: "Protected replenishment pick priority within current wave plan",
      metrics: [
        { label: "DC",               value: "Joliet DC · 93% capacity" },
        { label: "Trailer dwell",    value: "19.1 hrs (target 12 hrs)" },
        { label: "Stores exposed",   value: "58 Midwest stores" },
        { label: "Approval needed",  value: "Only if overtime required" },
        { label: "Timestamp",        value: "Today · 8:32 AM" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Without replenishment protection, Joliet pick-wave pressure would delay everyday SKU flow to 58 Midwest stores, degrading everyday service levels.",
      recommendedAction: "Confirm replenishment priority is reflected in the Joliet wave plan. If overtime is needed, approve via the labor flex approval.",
      guardrailNote: "Replenishment prioritization is within autonomous guardrails. Additional labor or overtime requires separate approval.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "dc-ai-3",
    title: "Flagged compressed promo delivery windows",
    segment: "Promo / Merchant-Driven",
    sourceTab: "DC Capacity & Transportation",
    sourceTabId: "dc-capacity",
    detected: "Promo delivery windows compressed on Northeast routes, risking display timing",
    actionTaken: "Linked route risk to promo display timing dependency",
    status: "watchlist",
    drawer: {
      title: "Flagged compressed promo delivery windows",
      status: "watchlist",
      explanation: "AI detected that Chesapeake DC outbound windows on Northeast routes are compressed, with 88% trailer utilization and 9 late routes. Promo / Merchant-Driven inventory may arrive after display setup deadlines — rendering the allocation plan ineffective at the store level.",
      signals: ["Chesapeake DC 87% capacity", "15.7 hrs trailer dwell", "88% trailer utilization on Northeast routes", "9 late routes flagged", "Promo display timing dependency", "14 stores at risk"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }, { label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "dc-capacity",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Protect promo delivery windows before display setup deadlines",
      metrics: [
        { label: "DC",               value: "Chesapeake DC · 87% capacity" },
        { label: "Trailer dwell",    value: "15.7 hrs" },
        { label: "Late routes",      value: "9 on Northeast lanes" },
        { label: "Stores at risk",   value: "14" },
        { label: "Timestamp",        value: "Today · 8:36 AM" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Compressed delivery windows risk late promo arrival, causing display setup failure and degraded promo sell-through at 14 Northeast stores.",
      recommendedAction: "Approve overflow route capacity for Chesapeake → Northeast priority lanes.",
      guardrailNote: "Watchlist — route risk flagged and linked to display timing dependency. No route change committed without approval.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for Review",
    },
  },
]

export const dcApprovals: ApprovalItem[] = [
  {
    id: "dc-ap-1",
    title: "Approve Savannah outbound wave change",
    segment: "Seasonal / Event",
    recommendation: "Re-sequence Savannah outbound waves to prioritize 72 high-risk Southeast stores",
    whyApproval: "Operational tradeoff may delay lower-priority shipments and requires DC manager sign-off",
    valueAtRisk: "$1.2M",
    owner: "DC Operations",
    status: "pending",
    drawer: {
      title: "Approve Savannah outbound wave change",
      status: "pending",
      explanation: "Savannah DC shipping dock utilization is above effective capacity while Seasonal / Event outbound waves are due before the allocation lock. Re-sequencing outbound waves to prioritize high-risk stores may delay lower-priority shipments and requires DC operations sign-off.",
      signals: ["Savannah DC 96% capacity", "22.4 hrs trailer dwell", "72 Southeast stores at risk", "$1.2M service exposure", "Allocation lock: Jun 10"],
      sourceTabs: [
        { label: "DC Capacity & Transportation", id: "dc-capacity" },
        { label: "Inventory & Allocation", id: "inventory" },
        { label: "Store Execution", id: "store-execution" },
      ],
      primarySourceTabId: "dc-capacity",
      segment: "Seasonal / Event",
      segmentStrategy: "Wave re-sequencing to protect Seasonal / Event outbound before selling window",
      metrics: [
        { label: "DC",             value: "Savannah DC" },
        { label: "Capacity",       value: "96%" },
        { label: "Trailer dwell",  value: "22.4 hrs" },
        { label: "Stores at risk", value: "72" },
        { label: "Value at risk",  value: "$1.2M" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$1.2M service exposure and 72 Southeast stores may miss priority Seasonal / Event delivery windows before the selling period.",
      recommendedAction: "Approve outbound wave re-sequencing and notify Inventory & Allocation.",
      guardrailNote: "No wave change executed without DC manager and planning sign-off.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "dc-ap-2",
    title: "Approve overflow route capacity",
    segment: "Seasonal / Event + Promo / Merchant-Driven",
    recommendation: "Add overflow route capacity for priority segment shipments from Savannah and Chesapeake",
    whyApproval: "Incremental transportation cost requires management approval",
    valueAtRisk: "$640K",
    owner: "Transportation Planning",
    status: "needs-approval",
    drawer: {
      title: "Approve overflow route capacity",
      status: "needs-approval",
      explanation: "Trailer utilization is high on Savannah (97%) and Chesapeake (88%) outbound lanes, compressing delivery windows for Seasonal / Event and Promo / Merchant-Driven priority shipments. Adding overflow route capacity protects delivery timing but incurs incremental transportation cost requiring management approval.",
      signals: ["Savannah → Southeast: 97% trailer utilization, 18 late routes", "Chesapeake → Northeast: 88% trailer utilization, 9 late routes", "Priority segments at delivery risk", "Incremental cost tradeoff"],
      sourceTabs: [
        { label: "DC Capacity & Transportation", id: "dc-capacity" },
        { label: "Store Execution", id: "store-execution" },
      ],
      primarySourceTabId: "dc-capacity",
      segment: "Seasonal / Event + Promo / Merchant-Driven",
      segmentStrategy: "Overflow route capacity for constrained priority lanes",
      metrics: [
        { label: "Lanes at risk",    value: "Savannah → SE, Chesapeake → NE" },
        { label: "Trailer util.",    value: "97% / 88%" },
        { label: "Value at risk",    value: "$640K" },
        { label: "Cost tradeoff",    value: "Incremental route capacity" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$640K delivery exposure tied to Seasonal / Event and Promo / Merchant-Driven shipments. Late deliveries may affect store readiness and promo execution.",
      recommendedAction: "Approve overflow route capacity for priority lanes only.",
      guardrailNote: "No incremental capacity committed without management and cost approval.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "dc-ap-3",
    title: "Approve labor flex for Olive Branch backlog",
    segment: "Consistent Replenishment",
    recommendation: "Flex labor coverage to reduce appointment backlog and protect replenishment flow",
    whyApproval: "Labor scheduling and overtime require operations approval",
    valueAtRisk: "$480K",
    owner: "DC Operations + Labor Planning",
    status: "pending",
    drawer: {
      title: "Approve labor flex for Olive Branch backlog",
      status: "pending",
      explanation: "Labor coverage and appointment backlog at Olive Branch DC (88% capacity, 16.2 hrs dwell) may limit outbound replenishment flow for Consistent Replenishment and Constrained / Exception SKUs. Flexing labor coverage for targeted shifts would reduce the backlog but requires operations approval for scheduling and any overtime.",
      signals: ["Olive Branch DC 88% capacity", "16.2 hrs trailer dwell", "Labor coverage gap identified", "Appointment backlog building", "Consistent Replenishment + Constrained / Exception at risk"],
      sourceTabs: [
        { label: "DC Capacity & Transportation", id: "dc-capacity" },
        { label: "Inventory & Allocation", id: "inventory" },
      ],
      primarySourceTabId: "dc-capacity",
      segment: "Consistent Replenishment",
      segmentStrategy: "Targeted labor flex to clear appointment backlog",
      metrics: [
        { label: "DC",             value: "Olive Branch DC" },
        { label: "Capacity",       value: "88%" },
        { label: "Trailer dwell",  value: "16.2 hrs" },
        { label: "Value at risk",  value: "$480K" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$480K exposure tied to delayed Consistent Replenishment flow. Everyday replenishment may fall behind service thresholds without labor flex.",
      recommendedAction: "Approve labor flex coverage for targeted shifts only.",
      guardrailNote: "No labor scheduling change committed without operations sign-off.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for Review",
    },
  },
]

// ─── STORE EXECUTION ─────────────────────────────────────────────────────────

export const storeActions: AIAction[] = [
  {
    id: "se-ai-1",
    title: "Linked display readiness to Promo / Merchant-Driven allocation",
    segment: "Promo / Merchant-Driven",
    sourceTab: "Store Execution",
    sourceTabId: "store-execution",
    detected: "Promo display completion below threshold in subset of stores",
    actionTaken: "Flagged stores where allocation should depend on display readiness confirmation",
    status: "watchlist",
    drawer: {
      title: "Linked display readiness to Promo / Merchant-Driven allocation",
      status: "watchlist",
      explanation: "AI detected that display readiness for Promo / Merchant-Driven SKU families is below threshold across a subset of stores. Allocating before display setup creates backroom overflow and wasted allocation capacity.",
      signals: ["Display readiness below threshold", "Promo / Merchant-Driven segment", "Allocation lock approaching", "Backroom overflow risk"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "store-execution",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Delay promo push pending display readiness confirmation",
      metrics: [{ label: "Segment", value: "Promo / Merchant-Driven" }, { label: "Value at risk", value: "$520K" }, { label: "Dependency", value: "Display readiness" }],
      humanApprovalRequired: true,
      businessImpact: "Early allocation without display readiness degrades promo sell-through and wastes allocation capacity.",
      recommendedAction: "Approve the display-readiness dependency rule below.",
      guardrailNote: "Watchlist — dependency flagged. No allocation delayed without approval.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "se-ai-2",
    title: "Detected backroom aging for Seasonal / Event SKUs",
    segment: "Seasonal / Event",
    sourceTab: "Store Execution",
    sourceTabId: "store-execution",
    detected: "Inventory aged over 48 hours in backroom across high-impact stores",
    actionTaken: "Created field action recommendation for backroom-to-shelf prioritization",
    status: "completed",
    drawer: {
      title: "Detected backroom aging for Seasonal / Event SKUs",
      status: "completed",
      explanation: "AI detected Seasonal / Event inventory sitting over 48 hours in backrooms at high-impact stores. Delayed backroom-to-shelf movement reduces effective shelf availability during the selling window.",
      signals: ["Seasonal / Event inventory aged >48 hours", "High-impact store subset", "Backroom aging threshold exceeded", "Selling window proximity"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "store-execution",
      segment: "Seasonal / Event",
      segmentStrategy: "Field action to prioritize backroom-to-shelf execution",
      metrics: [{ label: "Aging threshold", value: ">48 hours" }, { label: "Value at risk", value: "$1.8M" }, { label: "Segment", value: "Seasonal / Event" }],
      humanApprovalRequired: true,
      businessImpact: "Every hour of backroom aging during the selling window reduces effective sell-through — up to $1.8M at risk.",
      recommendedAction: "Approve field action for backroom aging below.",
      guardrailNote: "Field action recommendation is within guardrails. Store labor and DM sign-off required to execute.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "se-ai-3",
    title: "Identified phantom inventory risk for Constrained SKUs",
    segment: "Constrained / Exception",
    sourceTab: "Store Execution",
    sourceTabId: "store-execution",
    detected: "System inventory may not match physical shelf availability at select stores",
    actionTaken: "Created cycle count and verification recommendation for affected stores",
    status: "completed",
    drawer: {
      title: "Identified phantom inventory risk for Constrained SKUs",
      status: "completed",
      explanation: "AI detected signals suggesting that system-recorded inventory for Constrained / Exception SKUs may not match physical shelf availability at a subset of stores — creating phantom inventory that inflates availability metrics.",
      signals: ["System vs physical inventory discrepancy signals", "Constrained / Exception segment", "On-shelf availability anomaly", "Cycle count gap indicator"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "store-execution",
      segment: "Constrained / Exception",
      segmentStrategy: "Cycle count and inventory accuracy verification",
      metrics: [{ label: "Risk type", value: "Phantom inventory" }, { label: "Value at risk", value: "$780K" }, { label: "Verification needed", value: "Cycle count" }],
      humanApprovalRequired: true,
      businessImpact: "Phantom inventory causes over-reporting of shelf availability, masking real stockout risk for constrained SKUs.",
      recommendedAction: "Approve inventory accuracy verification and cycle count below.",
      guardrailNote: "Detection is autonomous. Cycle count and adjustment require store and inventory team sign-off.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
]

export const storeApprovals: ApprovalItem[] = [
  {
    id: "se-ap-1",
    title: "Approve display-readiness dependency rule",
    segment: "Promo / Merchant-Driven",
    recommendation: "Delay full promo push to stores without display readiness confirmation",
    whyApproval: "Field and merchandising agreement required — cannot automate store-level dependency",
    valueAtRisk: "$520K",
    owner: "Merchandising + Store Operations",
    status: "pending",
    drawer: {
      title: "Approve display-readiness dependency rule",
      status: "pending",
      explanation: "AI recommends creating a rule that delays full promo push to stores where display readiness is below threshold. This rule requires agreement from field and merchandising teams before it can be applied to allocation.",
      signals: ["Display readiness below threshold", "Promo / Merchant-Driven segment", "Field execution gap", "Merchandising sign-off needed"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "store-execution",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Display-gated promo push allocation",
      metrics: [{ label: "Value at risk", value: "$520K" }, { label: "Rule type", value: "Display-readiness dependency" }, { label: "Teams affected", value: "Field + Merchandising" }],
      humanApprovalRequired: true,
      businessImpact: "Approved rule prevents wasted allocation to stores that cannot execute promo display — protecting $520K in promo sell-through.",
      recommendedAction: "Approve dependency rule and communicate to district managers.",
      guardrailNote: "No allocation held without explicit field and merchandising sign-off.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "se-ap-2",
    title: "Approve field action for backroom aging",
    segment: "Seasonal / Event",
    recommendation: "Prioritize backroom-to-shelf execution for high-impact stores within 48 hours",
    whyApproval: "Requires store labor reallocation and district manager action — not automatable",
    valueAtRisk: "$1.8M",
    owner: "Store Operations + District Managers",
    status: "pending",
    drawer: {
      title: "Approve field action for backroom aging",
      status: "pending",
      explanation: "AI has identified Seasonal / Event inventory sitting >48 hours in backrooms at high-impact stores. Field action requires district manager direction and store labor reallocation — neither of which can be automated.",
      signals: ["Backroom aging >48 hours", "Seasonal / Event segment", "High-impact stores identified", "Selling window approaching"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "store-execution",
      segment: "Seasonal / Event",
      segmentStrategy: "Backroom-to-shelf field execution prioritization",
      metrics: [{ label: "Value at risk", value: "$1.8M" }, { label: "Aging threshold", value: ">48 hours" }, { label: "Action scope", value: "High-impact stores" }],
      humanApprovalRequired: true,
      businessImpact: "Approving and executing field action recovers up to $1.8M in Seasonal / Event sell-through by clearing backroom aging before the window closes.",
      recommendedAction: "Approve field action and communicate priority to district managers.",
      guardrailNote: "No field directive issued without DM and store operations sign-off.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "se-ap-3",
    title: "Approve inventory accuracy verification",
    segment: "Constrained / Exception",
    recommendation: "Create cycle count scope for stores with suspected phantom inventory",
    whyApproval: "Requires store execution and inventory adjustment — operational approval needed",
    valueAtRisk: "$780K",
    owner: "Store Operations + Inventory Control",
    status: "needs-approval",
    drawer: {
      title: "Approve inventory accuracy verification",
      status: "needs-approval",
      explanation: "AI has identified signals of phantom inventory for Constrained / Exception SKUs at a subset of stores. A cycle count is recommended to verify physical availability and correct system records. Operational approval required.",
      signals: ["System vs physical discrepancy signals", "Constrained / Exception segment", "Phantom inventory risk", "Cycle count scope identified"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "store-execution",
      segment: "Constrained / Exception",
      segmentStrategy: "Cycle count and system inventory correction",
      metrics: [{ label: "Value at risk", value: "$780K" }, { label: "Action", value: "Cycle count + adjustment" }, { label: "Teams", value: "Store Ops + Inventory Control" }],
      humanApprovalRequired: true,
      businessImpact: "Cycle count and correction ensures constrained SKU availability is accurately reported — preventing allocation decisions based on phantom stock.",
      recommendedAction: "Approve cycle count scope and schedule with store operations.",
      guardrailNote: "No inventory adjustment made without store and inventory control sign-off.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
]
