// ---------------------------------------------------------------------------
// AI Actions & Human Approvals — tab-specific data for AIActionsModule
// ---------------------------------------------------------------------------

import type { AIAction, ApprovalItem } from "./AIActionsModule"

// ─── EXECUTIVE CONTROL TOWER ─────────────────────────────────────────────────

export const ectActions: AIAction[] = [
  {
    id: "ect-ai-1",
    title: "Connected demand risk to allocation exposure",
    segment: "Seasonal / Event",
    sourceTab: "Demand Planning + Inventory",
    sourceTabId: "demand",
    detected: "Under-forecast bias running -8.9% linked to protected allocation need before window",
    actionTaken: "Linked demand risk signal to inventory allocation exposure across both tabs",
    status: "completed",
    drawer: {
      title: "Connected demand risk to allocation exposure",
      status: "completed",
      explanation: "AI detected that the under-forecast bias in Seasonal / Event SKUs is directly tied to under-allocation exposure. By linking the two signals, the AI created a cross-functional view of the revenue risk before the selling window.",
      signals: ["Forecast bias -8.9% vs actual velocity", "Seasonal / Event allocation readiness 72%", "Allocation lock deadline proximity", "214 stores with stockout exposure"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "demand",
      segment: "Seasonal / Event",
      segmentStrategy: "Pre-window push allocation with forecast uplift",
      metrics: [
        { label: "Forecast bias", value: "-8.9% vs actual" },
        { label: "Allocation readiness", value: "72%" },
        { label: "Stores at risk", value: "214" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Cross-linking demand and allocation signals surfaces the full $2.4M revenue exposure in one view.",
      recommendedAction: "Review the demand-allocation link in Demand Planning, then approve forecast uplift and push allocation.",
      guardrailNote: "Signal linkage is autonomous. No allocation or forecast change was made without approval.",
      actionLabel: "Go to Demand Planning",
      actionTabId: "demand",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "ect-ai-2",
    title: "Prioritized network constraints by segment impact",
    segment: "Seasonal / Event + Consistent Replenishment",
    sourceTab: "DC Capacity & Transportation",
    sourceTabId: "dc-capacity",
    detected: "Savannah and Joliet DC pressure affecting priority segment outbound flow",
    actionTaken: "Ranked Savannah and Joliet constraints by store service impact across segments",
    status: "completed",
    drawer: {
      title: "Prioritized network constraints by segment impact",
      status: "completed",
      explanation: "AI identified capacity pressure at Savannah (94%) and Joliet (91%) DCs and ranked these constraints by their impact on Seasonal / Event and Consistent Replenishment store service — surfacing the highest-value bottlenecks first.",
      signals: ["Savannah DC at 94% capacity", "Joliet DC at 91% capacity", "Seasonal / Event segment outbound priority", "Consistent Replenishment replenishment cycle at risk"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }],
      primarySourceTabId: "dc-capacity",
      segment: "Seasonal / Event + Consistent Replenishment",
      segmentStrategy: "Wave re-sequencing to protect priority segment outbound flow",
      metrics: [
        { label: "DCs with pressure", value: "Savannah, Joliet" },
        { label: "Outbound segments at risk", value: "Seasonal / Event, Consistent Replenishment" },
        { label: "Recommendation", value: "Wave re-sequencing" },
      ],
      humanApprovalRequired: false,
      businessImpact: "If not resolved, DC pressure delays on-time store delivery for 214 at-risk stores before the selling window.",
      recommendedAction: "Approve the Savannah outbound wave change and overflow route capacity in DC Capacity.",
      guardrailNote: "Constraint ranking is autonomous. Physical re-sequencing requires DC manager sign-off.",
      actionLabel: "Go to DC Capacity",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "ect-ai-3",
    title: "Flagged store execution dependency for promo push",
    segment: "Promo / Merchant-Driven",
    sourceTab: "Store Execution",
    sourceTabId: "store-execution",
    detected: "Promo display readiness below threshold in subset of stores",
    actionTaken: "Flagged display readiness as allocation dependency before promo push",
    status: "watchlist",
    drawer: {
      title: "Flagged store execution dependency for promo push",
      status: "watchlist",
      explanation: "AI detected that promo display completion is below threshold in a subset of stores, meaning full promo push allocation would arrive before stores are ready to execute — risking backroom overflow and wasted allocation.",
      signals: ["Display readiness below threshold", "Promo / Merchant-Driven segment classification", "Allocation lock approaching", "Store execution capacity constraint"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "store-execution",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Delay full promo push pending display readiness confirmation",
      metrics: [
        { label: "Segment", value: "Promo / Merchant-Driven" },
        { label: "Status", value: "Watchlist — no action taken" },
        { label: "Value at risk", value: "$520K" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Allocating before display readiness degrades promo sell-through and wastes allocation capacity.",
      recommendedAction: "Approve the display-readiness dependency rule to delay promo push for unready stores.",
      guardrailNote: "Watchlist status — flagged but no allocation decision delayed without human approval.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for review",
    },
  },
]

export const ectApprovals: ApprovalItem[] = [
  {
    id: "ect-ap-1",
    title: "Approve Seasonal forecast uplift and protected allocation",
    segment: "Seasonal / Event",
    recommendation: "Increase near-term forecast for selected Seasonal / Event SKU families and lock protected allocation before window",
    whyApproval: "High revenue exposure ahead of short selling window requires executive approval before allocation lock",
    valueAtRisk: "$2.4M",
    owner: "Demand Planning + Allocation",
    status: "pending",
    drawer: {
      title: "Approve Seasonal forecast uplift and protected allocation",
      status: "pending",
      explanation: "AI has recommended a forecast uplift for Seasonal / Event SKUs running 8.9% above baseline, and a protected pre-window push allocation to 214 at-risk stores. Both decisions require planner approval before allocation lock.",
      signals: ["Forecast bias -8.9%", "214 stores with stockout exposure", "Allocation lock approaching", "Revenue at risk: $2.4M"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "demand",
      segment: "Seasonal / Event",
      segmentStrategy: "Forecast uplift + protected pre-window push allocation",
      metrics: [
        { label: "Forecast bias", value: "-8.9%" },
        { label: "Revenue at risk", value: "$2.4M" },
        { label: "Stores affected", value: "214" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Approving unlocks correct allocation and protects up to $2.4M in Seasonal / Event revenue before the selling window closes.",
      recommendedAction: "Approve forecast uplift and protected allocation in Demand Planning.",
      guardrailNote: "AI will not commit inventory without explicit planner sign-off.",
      actionLabel: "Go to Demand Planning",
      actionTabId: "demand",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "ect-ap-2",
    title: "Approve inbound recovery for constrained SKUs",
    segment: "Constrained / Exception",
    recommendation: "Expedite delayed inbound PO and approve substitute SKUs where supplier fill-rate is short",
    whyApproval: "Inbound recovery tradeoffs and substitution decisions affect merchandising and allocation across stores",
    valueAtRisk: "$1.1M",
    owner: "Supplier Management + Inventory Planning",
    status: "needs-approval",
    drawer: {
      title: "Approve inbound recovery for constrained SKUs",
      status: "needs-approval",
      explanation: "AI has flagged 43 at-risk POs and fill-rate variance on Constrained / Exception SKUs. Recovery options include expedite and substitution — both require cross-functional approval due to cost and merchandising implications.",
      signals: ["43 at-risk POs", "Supplier fill-rate variance on priority SKUs", "Constrained / Exception segment flag", "Allocation lock approaching"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Constrained / Exception",
      segmentStrategy: "Human-reviewed fallback allocation with expedite or substitution",
      metrics: [
        { label: "At-risk POs", value: "43" },
        { label: "Revenue at risk", value: "$1.1M" },
        { label: "Recovery options", value: "Expedite + substitution" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Without recovery approval, constrained SKUs will result in partial allocation and lost revenue across affected stores.",
      recommendedAction: "Review PO risk in Supplier & Inbound Flow and approve substitute recovery or expedite.",
      guardrailNote: "No substitution or expedite action is taken without human approval.",
      actionLabel: "Go to Supplier & Inbound",
      actionTabId: "supplier-inbound",
      secondaryLabel: "Mark for review",
    },
  },
]

// ─── DEMAND PLANNING ─────────────────────────────────────────────────────────

export const demandActions: AIAction[] = [
  {
    id: "dp-ai-1",
    title: "Detected forecast bias by SKU segment",
    segment: "Seasonal / Event",
    sourceTab: "Demand Planning",
    sourceTabId: "demand",
    detected: "Forecast bias running -8.9% against actual velocity for Seasonal / Event SKUs",
    actionTaken: "Created uplift recommendation and linked it to revenue-at-risk calculation",
    status: "completed",
    drawer: {
      title: "Detected forecast bias by SKU segment",
      status: "completed",
      explanation: "AI detected that Seasonal / Event SKUs are running 8.9% above the baseline forecast. This under-forecast bias threatens allocation accuracy before the selling window and has been quantified as $2.4M in revenue exposure.",
      signals: ["Velocity delta +8.9% vs baseline forecast", "Seasonal / Event segment classification", "Allocation lock deadline proximity", "Historical seasonal bias pattern"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }],
      primarySourceTabId: "demand",
      segment: "Seasonal / Event",
      segmentStrategy: "Forecast uplift + protected pre-window push allocation",
      metrics: [
        { label: "Forecast bias", value: "-8.9% vs actual velocity" },
        { label: "Revenue at risk", value: "$2.4M" },
        { label: "Recommendation", value: "Forecast uplift + allocation push" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Under-forecast bias leads to under-allocation to high-velocity stores ahead of the selling window, causing lost sales.",
      recommendedAction: "Approve the forecast uplift in the Human Approval section below.",
      guardrailNote: "Bias detection is autonomous. Uplift requires planner approval before allocation lock.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dp-ai-2",
    title: "Separated stable from event-driven forecast logic",
    segment: "Consistent Replenishment + Seasonal / Event",
    sourceTab: "Demand Planning",
    sourceTabId: "demand",
    detected: "Stable SKUs require baseline replenishment; Seasonal SKUs require time-bound push logic",
    actionTaken: "Applied differentiated forecast treatment by segment",
    status: "completed",
    drawer: {
      title: "Separated stable from event-driven forecast logic",
      status: "completed",
      explanation: "AI identified that applying a single forecast model to both Consistent Replenishment and Seasonal / Event SKUs creates systematic error. Differentiated treatment was applied within planning guardrails.",
      signals: ["Segment classification from AI-Driven SKU Segmentation", "Forecast error rate differential by segment", "Selling window signal for Seasonal / Event", "Replenishment cycle signal for Consistent Replenishment"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "AI-Driven SKU Segmentation", id: "sku-segmentation" }],
      primarySourceTabId: "demand",
      segment: "Consistent Replenishment + Seasonal / Event",
      segmentStrategy: "Differentiated forecast logic by segment type",
      metrics: [
        { label: "Segments with differentiated logic", value: "2" },
        { label: "Forecast model", value: "Segment-specific applied" },
        { label: "Human approval required", value: "No" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Differentiated logic improves forecast accuracy for both segments and prevents under- or over-allocation.",
      recommendedAction: "No action required. Confirm differentiated forecast logic is reflected in planning outputs.",
      guardrailNote: "Differentiated treatment is within autonomous planning guardrails — no forecast or inventory commitment was made.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dp-ai-3",
    title: "Flagged low-confidence demand signals",
    segment: "Treasure Hunt / Limited Buy",
    sourceTab: "Demand Planning",
    sourceTabId: "demand",
    detected: "Sparse SKU history but similar-item analogs available",
    actionTaken: "Routed forecast logic to analog-based estimate pending planner review",
    status: "watchlist",
    drawer: {
      title: "Flagged low-confidence demand signals for limited-buy SKUs",
      status: "watchlist",
      explanation: "AI detected sparse demand history for Treasure Hunt / Limited Buy SKUs and identified similar-item analogs that can serve as a forecast basis. Analog-based forecasting was recommended and routed for approval due to markdown risk.",
      signals: ["Sparse SKU demand history", "Similar-item analog available", "Treasure Hunt / Limited Buy segment classification", "Markdown risk if over-forecasted"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }],
      primarySourceTabId: "demand",
      segment: "Treasure Hunt / Limited Buy",
      segmentStrategy: "Analog-based forecast pending human approval",
      metrics: [
        { label: "History depth", value: "Sparse" },
        { label: "Analog signal", value: "Available" },
        { label: "Value at risk", value: "$640K" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Without an approved forecast basis, these SKUs will be under-planned or over-planned, risking stockout or markdown.",
      recommendedAction: "Approve the analog-based forecast method below.",
      guardrailNote: "Watchlist — no forecast was committed. Analog method requires planner approval.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
]

export const demandApprovals: ApprovalItem[] = [
  {
    id: "dp-ap-1",
    title: "Approve Seasonal / Event forecast uplift",
    segment: "Seasonal / Event",
    recommendation: "Apply temporary +12% uplift for selected Southeast Seasonal / Event SKU families to correct -8.9% under-forecast bias",
    whyApproval: "High revenue exposure before short selling window requires planner sign-off",
    valueAtRisk: "$2.4M",
    owner: "Demand Planning",
    status: "pending",
    drawer: {
      title: "Approve Seasonal / Event forecast uplift",
      status: "pending",
      explanation: "Actual velocity and promotion lift are exceeding baseline demand assumptions for Southeast Seasonal / Event SKUs. AI has created an uplift recommendation. Human approval is required before any forecast or inventory commitment is made.",
      signals: ["Velocity delta +8.9% vs baseline", "Seasonal / Event segment", "Allocation lock approaching", "$2.4M revenue at risk", "38 stores exposed"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "demand",
      segment: "Seasonal / Event",
      segmentStrategy: "Forecast uplift before allocation lock",
      metrics: [
        { label: "Bias",            value: "-8.9% vs actual velocity" },
        { label: "Value at risk",   value: "$2.4M" },
        { label: "Stores at risk",  value: "38" },
        { label: "Uplift proposed", value: "+12% for selected Southeast stores" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$2.4M of revenue exposure and 38 stores at risk if uplift is not approved before forecast lock. Allocation may under-support high-velocity stores during the selling window.",
      recommendedAction: "Approve temporary +12% uplift and send to Inventory & Allocation for protected push allocation.",
      guardrailNote: "AI will not commit any forecast or allocation change without explicit planner approval.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dp-ap-2",
    title: "Approve Consistent Replenishment baseline adjustment",
    segment: "Consistent Replenishment",
    recommendation: "Increase 4-week baseline forecast by +6% for selected Midwest paper goods",
    whyApproval: "Impacts replenishment quantities and DC flow — requires planner and supply planning sign-off",
    valueAtRisk: "$1.7M",
    owner: "Demand Planning + Supply Planning",
    status: "pending",
    drawer: {
      title: "Approve Consistent Replenishment baseline adjustment",
      status: "pending",
      explanation: "Recent velocity acceleration suggests the baseline demand forecast is understated for selected Midwest paper goods. A +6% 4-week adjustment is recommended. This approval impacts replenishment quantities and DC flow.",
      signals: ["Velocity acceleration detected in Midwest pantry SKUs", "Bias: -6.7% vs actual", "27 stores with near-term gap", "DC flow timing dependency"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "DC Capacity & Transportation", id: "dc-capacity" }],
      primarySourceTabId: "demand",
      segment: "Consistent Replenishment",
      segmentStrategy: "Baseline correction + replenishment quantity adjustment",
      metrics: [
        { label: "Bias",              value: "-6.7% vs actual" },
        { label: "Value at risk",     value: "$1.7M" },
        { label: "Stores at risk",    value: "27" },
        { label: "Adjustment",        value: "+6% 4-week baseline" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$1.7M revenue exposure and 27 stores at risk. Replenishment quantities may remain below near-term demand if the baseline is not adjusted.",
      recommendedAction: "Approve +6% 4-week baseline adjustment and notify Supply Planning.",
      guardrailNote: "No replenishment quantity or DC flow change has been committed without approval.",
      actionLabel: "Go to DC Capacity & Transportation",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dp-ap-3",
    title: "Validate Promo / Merchant-Driven lift assumptions",
    segment: "Promo / Merchant-Driven",
    recommendation: "Confirm Party promo timing and expected lift before the next forecast lock",
    whyApproval: "Merchant calendar confirmation required before forecast can be locked",
    valueAtRisk: "$860K",
    owner: "Merchandising + Demand Planning",
    status: "needs-approval",
    drawer: {
      title: "Validate Promo / Merchant-Driven lift assumptions",
      status: "needs-approval",
      explanation: "Party endcap promotion timing shifted relative to the prior planning cycle. The current forecast may not reflect actual promo pull-through. Merchant confirmation is required before forecast lock.",
      signals: ["Circular timing shifted from prior cycle", "Promo lift assumption unvalidated", "14 stores with forecast uncertainty", "Forecast lock approaching"],
      sourceTabs: [{ label: "Demand Planning", id: "demand" }, { label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "demand",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Promo lift validation before forecast lock",
      metrics: [
        { label: "Bias",             value: "-5.2% vs baseline" },
        { label: "Value at risk",    value: "$860K" },
        { label: "Stores at risk",   value: "14" },
        { label: "Merchant sign-off", value: "Required" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$860K revenue exposure and 14 stores at risk. Forecast may not reflect promo lift, and stores may receive insufficient product for display execution.",
      recommendedAction: "Request merchant validation before forecast lock.",
      guardrailNote: "No forecast or allocation action taken until merchant confirms promo timing and lift assumptions.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for review",
    },
  },
]

// ─── INVENTORY & ALLOCATION ────────────────────────────────────────────────────

export const inventoryActions: AIAction[] = [
  {
    id: "inv-ai-1",
    title: "Ranked stores by absorption capacity",
    segment: "Seasonal / Event",
    sourceTab: "Inventory & Allocation",
    sourceTabId: "inventory",
    detected: "High-velocity stores can absorb larger pre-window push; lower-velocity stores risk backroom overflow",
    actionTaken: "Ranked store clusters by absorption capacity and service risk for Seasonal / Event allocation",
    status: "completed",
    drawer: {
      title: "Ranked stores by absorption capacity",
      status: "completed",
      explanation: "AI identified 214 stores with stockout exposure and ranked them by absorption capacity to ensure the Seasonal / Event push prioritizes the highest-risk stores. Store clusters with backroom overflow risk were identified and excluded from the push tier to prevent waste.",
      signals: ["214 stores at stockout risk", "Store absorption capacity scored by DC catchment", "Backroom overflow risk flagged at 42 lower-velocity stores", "Seasonal / Event segment classification"],
      sourceTabs: [{ label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "inventory",
      segment: "Seasonal / Event",
      segmentStrategy: "Tiered push by absorption rank — high-velocity stores first",
      metrics: [
        { label: "Stores ranked",      value: "214 at-risk" },
        { label: "High absorption",    value: "Tier 1 push candidates" },
        { label: "Timestamp",          value: "Today · 8:18 AM" },
        { label: "Human approval",     value: "Required before push release" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Proper store ranking ensures available inventory flows to highest-risk stores. Without ranking, even inventory and backroom overflow would reduce effective service.",
      recommendedAction: "Approve the Seasonal / Event push allocation in the Human Approval column.",
      guardrailNote: "Store ranking is autonomous within guardrails. Final push allocation release requires planner approval.",
    },
  },
  {
    id: "inv-ai-2",
    title: "Protected baseline replenishment volume",
    segment: "Consistent Replenishment",
    sourceTab: "Inventory & Allocation",
    sourceTabId: "inventory",
    detected: "Everyday SKUs need steady flow to prevent service degradation at high-velocity stores",
    actionTaken: "Protected replenishment volume for high-velocity stores within planning guardrails",
    status: "completed",
    drawer: {
      title: "Protected baseline replenishment volume",
      status: "completed",
      explanation: "AI identified that Consistent Replenishment SKUs were at risk of losing allocation volume to the Seasonal / Event push. Baseline replenishment volume was autonomously protected within planning guardrails to prevent service degradation at high-velocity Midwest stores.",
      signals: ["Consistent Replenishment segment at risk of allocation crowding", "High-velocity Midwest stores below coverage", "Baseline volume protection applied within guardrails", "No inventory committed — protection flag only"],
      sourceTabs: [{ label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "inventory",
      segment: "Consistent Replenishment",
      segmentStrategy: "Protected baseline replenishment before seasonal push competes for volume",
      metrics: [
        { label: "Protection applied",  value: "Consistent Replenishment volume" },
        { label: "Timestamp",           value: "Today · 8:21 AM" },
        { label: "Human approval",      value: "Not required for protection flag" },
        { label: "Next step",           value: "Confirm in final allocation plan" },
      ],
      humanApprovalRequired: false,
      businessImpact: "Without protection, Consistent Replenishment SKUs would have lost allocation to the Seasonal / Event push, degrading everyday service levels at high-velocity stores.",
      recommendedAction: "Confirm replenishment protection is reflected in the final allocation plan before lock.",
      guardrailNote: "Protection is autonomous and within guardrails. No inventory committed without human approval.",
    },
  },
  {
    id: "inv-ai-3",
    title: "Flagged constrained allocation fallback scenario",
    segment: "Constrained / Exception",
    sourceTab: "Inventory & Allocation",
    sourceTabId: "inventory",
    detected: "Recommended allocation exceeds available executable supply for constrained SKUs",
    actionTaken: "Created fallback allocation scenario for planner review",
    status: "watchlist",
    drawer: {
      title: "Flagged constrained allocation fallback scenario",
      status: "watchlist",
      explanation: "AI detected that the recommended allocation for Constrained / Exception SKUs exceeds available executable supply, likely due to supplier fill-rate variance. A fallback allocation scenario with partial fulfillment and substitution options was created but not committed — requires planner review before any allocation action.",
      signals: ["Recommended allocation exceeds executable supply", "Supplier fill-rate variance detected", "Constrained / Exception segment", "Fallback scenario created — not committed"],
      sourceTabs: [{ label: "Inventory & Allocation", id: "inventory" }, { label: "Supplier & Inbound Flow", id: "supplier-inbound" }],
      primarySourceTabId: "inventory",
      segment: "Constrained / Exception",
      segmentStrategy: "Human-reviewed fallback with partial allocation and substitution",
      metrics: [
        { label: "Supply gap",       value: "Exceeds executable supply" },
        { label: "Value at risk",    value: "$1.1M" },
        { label: "Timestamp",        value: "Today · 8:25 AM" },
        { label: "Fallback status",  value: "Created — not committed" },
      ],
      humanApprovalRequired: true,
      businessImpact: "Without an approved fallback, constrained SKUs will result in partial and inconsistent allocation across stores with no visibility into priority.",
      recommendedAction: "Approve the constrained fallback allocation scenario in the Human Approval column.",
      guardrailNote: "Watchlist — fallback created but no allocation committed without explicit planner approval.",
      actionLabel: "Go to Supplier & Inbound Flow",
      actionTabId: "supplier-inbound",
    },
  },
]

export const inventoryApprovals: ApprovalItem[] = [
  {
    id: "inv-ap-1",
    title: "Approve Seasonal / Event protected push allocation",
    segment: "Seasonal / Event",
    recommendation: "Reserve $3.6M of available Seasonal / Event inventory for 72 high-risk Southeast stores",
    whyApproval: "High service exposure and constrained inventory require planner decision on store prioritization",
    valueAtRisk: "$2.8M",
    owner: "Allocation Planning",
    status: "pending",
    drawer: {
      title: "Approve Seasonal / Event protected push allocation",
      status: "pending",
      explanation: "Demand Planning identified a Seasonal / Event under-forecast in the Southeast, while Savannah DC has limited available inventory. AI has ranked 72 high-risk stores by absorption capacity and recommends protecting inventory for those stores before allocation lock. Approval required before any inventory is committed.",
      signals: ["72 stores ranked by absorption capacity", "Savannah DC constrained", "$3.6M shortage vs target", "Allocation lock: Jun 10", "$2.8M service risk"],
      sourceTabs: [
        { label: "Demand Planning", id: "demand" },
        { label: "DC Capacity & Transportation", id: "dc-capacity" },
        { label: "Store Execution", id: "store-execution" },
      ],
      primarySourceTabId: "inventory",
      segment: "Seasonal / Event",
      segmentStrategy: "Protected pre-window push to high-absorption stores",
      metrics: [
        { label: "Stores at risk",    value: "72" },
        { label: "Inventory short",   value: "$3.6M vs target" },
        { label: "Value at risk",     value: "$2.8M service risk" },
        { label: "Allocation lock",   value: "Jun 10" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$2.8M service risk and 72 stores exposed if protected allocation is not approved before the Jun 10 allocation lock. High-velocity stores may not receive enough inventory during the seasonal selling window.",
      recommendedAction: "Approve protected push allocation and send priority flow to DC Capacity & Transportation.",
      guardrailNote: "No inventory committed without explicit planner approval.",
      actionLabel: "Go to DC Capacity & Transportation",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "inv-ap-2",
    title: "Approve constrained fallback allocation",
    segment: "Constrained / Exception",
    recommendation: "Partially allocate supplier-limited cleaning SKUs and substitute where possible",
    whyApproval: "Tradeoff across stores and SKU families requires planner decision; not safe to fully automate",
    valueAtRisk: "$1.1M",
    owner: "Inventory Planning",
    status: "needs-approval",
    drawer: {
      title: "Approve constrained fallback allocation",
      status: "needs-approval",
      explanation: "Supplier and inventory constraints prevent the full recommended allocation for Constrained / Exception SKUs from being executed. AI created a fallback scenario with partial allocation and substitution options. The tradeoff across stores and SKU families is not safely automatable — requires planner decision.",
      signals: ["Full allocation not executable", "Supplier fill-rate short on priority SKUs", "Partial allocation scenario created", "$1.1M value at risk"],
      sourceTabs: [
        { label: "Inventory & Allocation", id: "inventory" },
        { label: "Supplier & Inbound Flow", id: "supplier-inbound" },
      ],
      primarySourceTabId: "inventory",
      segment: "Constrained / Exception",
      segmentStrategy: "Partial allocation + SKU substitution where available",
      metrics: [
        { label: "Value at risk",     value: "$1.1M" },
        { label: "Recovery options",  value: "Partial + substitution" },
        { label: "Stores affected",   value: "Constrained SKU families" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$1.1M exposure tied to constrained cleaning SKUs. Inventory may be spread too thinly or sent to lower-priority stores without approved guidance.",
      recommendedAction: "Approve partial allocation and substitution logic.",
      guardrailNote: "No substitution or partial allocation committed without explicit approval.",
      actionLabel: "Go to Supplier & Inbound Flow",
      actionTabId: "supplier-inbound",
      secondaryLabel: "Mark for Review",
    },
  },
  {
    id: "inv-ap-3",
    title: "Approve Treasure Hunt controlled transfer",
    segment: "Treasure Hunt / Limited Buy",
    recommendation: "Transfer $1.4M of limited-buy home goods from Marietta DC to the Southeast demand pool",
    whyApproval: "Sparse SKU history, markdown risk, trailer availability, and receiving capacity require planner sign-off",
    valueAtRisk: "$720K",
    owner: "Inventory Planning + Transportation",
    status: "pending",
    drawer: {
      title: "Approve Treasure Hunt controlled transfer",
      status: "pending",
      explanation: "Limited-buy home goods are above target in Southwest while Southeast has stronger absorption potential. AI recommends transferring $1.4M of excess inventory from Marietta DC to the Southeast demand pool. Transfer affects DC capacity and transportation schedule — requires planner approval.",
      signals: ["$4.2M above target at Marietta DC", "Southeast absorption pool has capacity", "Transfer route: Marietta → Savannah DC", "Trailer availability and receiving capacity dependency"],
      sourceTabs: [
        { label: "DC Capacity & Transportation", id: "dc-capacity" },
      ],
      primarySourceTabId: "inventory",
      segment: "Treasure Hunt / Limited Buy",
      segmentStrategy: "Controlled transfer from overstock to high-absorption demand region",
      metrics: [
        { label: "Transfer amount",   value: "$1.4M" },
        { label: "Overstock pool",    value: "$4.2M at Marietta DC" },
        { label: "Carrying risk",     value: "$720K if not transferred" },
        { label: "Transfer route",    value: "Marietta → Savannah DC" },
      ],
      humanApprovalRequired: true,
      businessImpact: "$720K carrying risk and markdown exposure if excess inventory remains in the Southwest. Higher-absorption stores in Southeast remain under-supported.",
      recommendedAction: "Approve transfer subject to transportation and receiving capacity.",
      guardrailNote: "No transfer committed without explicit approval. Transportation and DC schedule must be confirmed.",
      actionLabel: "Go to DC Capacity & Transportation",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for Review",
    },
  },
]

// ─── SUPPLIER & INBOUND FLOW ───────────────────────────────────────────────────

export const supplierActions: AIAction[] = [
  {
    id: "si-ai-1",
    title: "Linked PO risk to SKU segment impact",
    segment: "Constrained / Exception",
    sourceTab: "Supplier & Inbound Flow",
    sourceTabId: "supplier-inbound",
    detected: "Supplier fill-rate variance on 43 at-risk POs affecting priority SKU families",
    actionTaken: "Connected at-risk POs to allocation and revenue exposure across planning modules",
    status: "completed",
    drawer: {
      title: "Linked PO risk to SKU segment impact",
      status: "completed",
      explanation: "AI identified 43 at-risk POs with fill-rate variance on Constrained / Exception SKU families and connected these inbound constraints to active allocation decisions — surfacing the full downstream impact.",
      signals: ["43 at-risk POs", "Supplier fill-rate variance", "Constrained / Exception segment", "Linked to allocation decisions"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Constrained / Exception",
      segmentStrategy: "Human-reviewed fallback with expedite or substitution",
      metrics: [{ label: "At-risk POs", value: "43" }, { label: "Fill-rate variance", value: "On priority SKUs" }, { label: "Downstream allocation", value: "3 open approvals" }],
      humanApprovalRequired: false,
      businessImpact: "Linking PO risk to allocation surfaces $1.1M in downstream exposure that would otherwise be invisible at planning review.",
      recommendedAction: "Review constrained POs and approve recovery actions below.",
      guardrailNote: "Signal linking is autonomous. Recovery action requires planner and supplier sign-off.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "si-ai-2",
    title: "Flagged inbound timing risk for Seasonal / Event SKUs",
    segment: "Seasonal / Event",
    sourceTab: "Supplier & Inbound Flow",
    sourceTabId: "supplier-inbound",
    detected: "Inbound ETA variance on Savannah DC seasonal PO may miss selling window",
    actionTaken: "Recommended expedite review for critical seasonal inbound PO",
    status: "watchlist",
    drawer: {
      title: "Flagged inbound timing risk for Seasonal / Event SKUs",
      status: "watchlist",
      explanation: "AI detected ETA variance on a critical Seasonal / Event inbound PO into Savannah DC. If the delay persists, the inventory may arrive after the selling window opens, negating the push allocation strategy.",
      signals: ["Inbound ETA variance on Savannah DC PO", "Seasonal / Event segment", "Selling window proximity", "Expedite cost vs revenue tradeoff"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Seasonal / Event",
      segmentStrategy: "Expedite critical inbound PO to protect selling window",
      metrics: [{ label: "At-risk PO", value: "Savannah DC seasonal" }, { label: "Value at risk", value: "$1.6M" }, { label: "Status", value: "Watchlist — expedite pending" }],
      humanApprovalRequired: true,
      businessImpact: "Late inbound delivery renders the protected allocation strategy ineffective — up to $1.6M in seasonal revenue at risk.",
      recommendedAction: "Approve expedite for the delayed seasonal PO below.",
      guardrailNote: "Watchlist — no expedite committed without cost approval.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "si-ai-3",
    title: "Identified supplier risk for baseline replenishment",
    segment: "Consistent Replenishment",
    sourceTab: "Supplier & Inbound Flow",
    sourceTabId: "supplier-inbound",
    detected: "Short shipment on everyday SKU PO threatens steady replenishment flow",
    actionTaken: "Prioritized recovery by store service impact and surfaced for planner review",
    status: "completed",
    drawer: {
      title: "Identified supplier risk for baseline replenishment",
      status: "completed",
      explanation: "AI detected a short shipment affecting Consistent Replenishment SKUs and prioritized recovery actions by store service impact to prevent service degradation at high-velocity stores.",
      signals: ["Short shipment on everyday SKU PO", "Consistent Replenishment segment", "High-velocity store service risk", "Replenishment cycle timing"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Consistent Replenishment",
      segmentStrategy: "Service-impact-ranked recovery for baseline replenishment",
      metrics: [{ label: "Segment", value: "Consistent Replenishment" }, { label: "Impact", value: "Everyday SKU replenishment" }, { label: "Recovery", value: "Prioritized by store service" }],
      humanApprovalRequired: false,
      businessImpact: "Short shipment on everyday SKUs creates service gaps at high-velocity stores if not recovered before next replenishment cycle.",
      recommendedAction: "Review recovery priority list and confirm replenishment flow plan.",
      guardrailNote: "Priority ranking is autonomous. Recovery action requires supplier and planning confirmation.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
]

export const supplierApprovals: ApprovalItem[] = [
  {
    id: "si-ap-1",
    title: "Approve expedite for Seasonal / Event inbound PO",
    segment: "Seasonal / Event",
    recommendation: "Expedite delayed inbound PO into Savannah DC to protect selling window timing",
    whyApproval: "Operating cost tradeoff on expedite requires management approval",
    valueAtRisk: "$1.6M",
    owner: "Supplier Management",
    status: "pending",
    drawer: {
      title: "Approve expedite for Seasonal / Event inbound PO",
      status: "pending",
      explanation: "A critical Seasonal / Event PO destined for Savannah DC has inbound ETA variance. Expedite is recommended to protect the selling window. Approval required due to operating cost tradeoff.",
      signals: ["ETA variance on Savannah DC seasonal PO", "Selling window approaching", "Expedite cost vs $1.6M revenue", "Seasonal / Event segment priority"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Seasonal / Event",
      segmentStrategy: "Expedite to protect selling window",
      metrics: [{ label: "Value at risk", value: "$1.6M" }, { label: "Recovery option", value: "Expedite" }, { label: "Cost tradeoff", value: "Approval required" }],
      humanApprovalRequired: true,
      businessImpact: "Expedite protects $1.6M in seasonal revenue by ensuring inventory arrives before the selling window.",
      recommendedAction: "Approve expedite request and coordinate with Savannah DC receiving.",
      guardrailNote: "No expedite action taken without cost and operational sign-off.",
      actionLabel: "Go to DC Capacity",
      actionTabId: "dc-capacity",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "si-ap-2",
    title: "Approve substitute recovery for constrained SKUs",
    segment: "Constrained / Exception",
    recommendation: "Use substitute SKUs where supplier fill-rate is short on Constrained / Exception families",
    whyApproval: "Substitution affects merchandising and allocation decisions — requires cross-functional approval",
    valueAtRisk: "$1.1M",
    owner: "Supplier Mgmt + Inventory Planning",
    status: "needs-approval",
    drawer: {
      title: "Approve substitute recovery for constrained SKUs",
      status: "needs-approval",
      explanation: "AI recommends substituting alternative SKUs where Constrained / Exception supplier fill-rate is short. Substitution impacts merchandising, store allocation, and planogram compliance — requiring cross-functional approval.",
      signals: ["Constrained / Exception fill-rate short", "43 at-risk POs", "Substitute SKU candidates identified", "Merchandising impact"],
      sourceTabs: [{ label: "Supplier & Inbound Flow", id: "supplier-inbound" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "supplier-inbound",
      segment: "Constrained / Exception",
      segmentStrategy: "Substitute SKU recovery for supplier-constrained families",
      metrics: [{ label: "At-risk POs", value: "43" }, { label: "Value at risk", value: "$1.1M" }, { label: "Substitution impact", value: "Merchandising + allocation" }],
      humanApprovalRequired: true,
      businessImpact: "Approved substitution recovers up to $1.1M in constrained SKU revenue and maintains store service levels.",
      recommendedAction: "Review substitute SKU candidates and approve the recovery plan.",
      guardrailNote: "No substitution committed without merchandising and planning sign-off.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
]

// ─── DC CAPACITY & TRANSPORTATION ────────────────────────────────────────────

export const dcActions: AIAction[] = [
  {
    id: "dc-ai-1",
    title: "Prioritized outbound waves by SKU segment",
    segment: "Seasonal / Event",
    sourceTab: "DC Capacity & Transportation",
    sourceTabId: "dc-capacity",
    detected: "Savannah DC shipping pressure delaying Seasonal / Event priority outbound shipments",
    actionTaken: "Recommended wave re-sequencing for high-risk Seasonal / Event store shipments",
    status: "completed",
    drawer: {
      title: "Prioritized outbound waves by SKU segment",
      status: "completed",
      explanation: "AI detected that Savannah DC capacity pressure (94%) is causing delays to Seasonal / Event priority shipments. Wave re-sequencing was recommended to ensure highest-impact stores receive shipments before the selling window.",
      signals: ["Savannah DC at 94% capacity", "Seasonal / Event outbound priority", "Selling window proximity", "High-risk store delivery timing"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }],
      primarySourceTabId: "dc-capacity",
      segment: "Seasonal / Event",
      segmentStrategy: "Wave re-sequencing by segment and store risk priority",
      metrics: [{ label: "DC capacity", value: "Savannah 94%" }, { label: "Segment priority", value: "Seasonal / Event" }, { label: "Recommendation", value: "Wave re-sequencing" }],
      humanApprovalRequired: true,
      businessImpact: "Delayed Seasonal / Event shipments from Savannah risk on-time store delivery for 214 at-risk stores.",
      recommendedAction: "Approve the Savannah outbound wave change below.",
      guardrailNote: "Re-sequencing recommendation is within planning guardrails. Physical execution requires DC manager confirmation.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dc-ai-2",
    title: "Protected baseline replenishment flow at Joliet DC",
    segment: "Consistent Replenishment",
    sourceTab: "DC Capacity & Transportation",
    sourceTabId: "dc-capacity",
    detected: "Joliet pick-wave pressure affecting everyday SKU replenishment cycle",
    actionTaken: "Prioritized Consistent Replenishment picks within Joliet wave sequencing",
    status: "completed",
    drawer: {
      title: "Protected baseline replenishment flow at Joliet DC",
      status: "completed",
      explanation: "AI detected pick-wave pressure at Joliet DC (91%) threatening Consistent Replenishment flow. Replenishment picks were prioritized within wave sequencing to maintain everyday SKU service levels.",
      signals: ["Joliet DC at 91% capacity", "Consistent Replenishment replenishment cycle", "Pick-wave pressure", "Everyday SKU service risk"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }],
      primarySourceTabId: "dc-capacity",
      segment: "Consistent Replenishment",
      segmentStrategy: "Protected replenishment pick priority within DC wave",
      metrics: [{ label: "DC capacity", value: "Joliet 91%" }, { label: "Segment", value: "Consistent Replenishment" }, { label: "Action", value: "Replenishment picks prioritized" }],
      humanApprovalRequired: false,
      businessImpact: "Without protection, Joliet capacity pressure would delay everyday SKU replenishment, degrading store service levels.",
      recommendedAction: "Confirm replenishment priority is reflected in Joliet wave plan.",
      guardrailNote: "Replenishment priority is within autonomous guardrails — no delivery commitment was changed.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dc-ai-3",
    title: "Flagged compressed promo delivery windows on Northeast routes",
    segment: "Promo / Merchant-Driven",
    sourceTab: "DC Capacity & Transportation",
    sourceTabId: "dc-capacity",
    detected: "Promo delivery windows compressed on Northeast routes, risking display timing",
    actionTaken: "Linked route risk to promo display timing dependency",
    status: "watchlist",
    drawer: {
      title: "Flagged compressed promo delivery windows on Northeast routes",
      status: "watchlist",
      explanation: "AI detected that delivery windows on Northeast transportation routes are compressed, creating risk that Promo / Merchant-Driven inventory will arrive after display setup deadlines — making allocation ineffective.",
      signals: ["Compressed delivery windows on Northeast routes", "Promo / Merchant-Driven segment", "Display setup timing dependency", "Route capacity constraint"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }, { label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "dc-capacity",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Route capacity approval to protect promo delivery timing",
      metrics: [{ label: "Routes affected", value: "Northeast" }, { label: "Segment", value: "Promo / Merchant-Driven" }, { label: "Dependency", value: "Display timing" }],
      humanApprovalRequired: true,
      businessImpact: "Compressed delivery windows risk late promo arrival, causing display setup failure and degraded promo sell-through.",
      recommendedAction: "Approve overflow route capacity to protect promo delivery timing.",
      guardrailNote: "Watchlist — route risk flagged. No route change committed without approval.",
      actionLabel: "Go to Store Execution",
      actionTabId: "store-execution",
      secondaryLabel: "Mark for review",
    },
  },
]

export const dcApprovals: ApprovalItem[] = [
  {
    id: "dc-ap-1",
    title: "Approve Savannah outbound wave change",
    segment: "Seasonal / Event",
    recommendation: "Re-sequence outbound waves at Savannah DC to prioritize high-risk Seasonal / Event store shipments",
    whyApproval: "Operational tradeoff — re-sequencing may delay lower-priority shipments and requires DC manager sign-off",
    valueAtRisk: "$1.2M",
    owner: "DC Operations",
    status: "pending",
    drawer: {
      title: "Approve Savannah outbound wave change",
      status: "pending",
      explanation: "AI recommends re-sequencing Savannah DC outbound waves to prioritize Seasonal / Event high-risk stores before the selling window. This operational change requires DC manager approval due to tradeoffs with lower-priority shipments.",
      signals: ["Savannah DC 94% capacity", "Seasonal / Event outbound priority", "214 at-risk stores", "$1.2M value at risk"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }],
      primarySourceTabId: "dc-capacity",
      segment: "Seasonal / Event",
      segmentStrategy: "Wave re-sequencing to protect Seasonal / Event outbound before window",
      metrics: [{ label: "DC", value: "Savannah" }, { label: "Value at risk", value: "$1.2M" }, { label: "Tradeoff", value: "Lower-priority shipment delay" }],
      humanApprovalRequired: true,
      businessImpact: "Approved re-sequencing protects $1.2M in Seasonal / Event on-time delivery before the selling window.",
      recommendedAction: "Approve wave re-sequencing and coordinate with Savannah DC manager.",
      guardrailNote: "No wave change executed without DC manager and planning sign-off.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "dc-ap-2",
    title: "Approve overflow route capacity for priority segments",
    segment: "Seasonal / Event + Promo / Merchant-Driven",
    recommendation: "Add route capacity for Seasonal / Event and Promo / Merchant-Driven shipments on constrained lanes",
    whyApproval: "Incremental transportation cost requires management approval",
    valueAtRisk: "$640K",
    owner: "Transportation Planning",
    status: "needs-approval",
    drawer: {
      title: "Approve overflow route capacity for priority segments",
      status: "needs-approval",
      explanation: "AI recommends adding overflow route capacity on constrained Northeast and Southeast lanes to protect delivery timing for Seasonal / Event and Promo / Merchant-Driven priority shipments. The incremental cost requires management approval.",
      signals: ["Compressed delivery windows on constrained lanes", "Seasonal / Event + Promo / Merchant-Driven segment priority", "Route capacity constraint", "Incremental cost tradeoff"],
      sourceTabs: [{ label: "DC Capacity & Transportation", id: "dc-capacity" }],
      primarySourceTabId: "dc-capacity",
      segment: "Seasonal / Event + Promo / Merchant-Driven",
      segmentStrategy: "Overflow route capacity for priority segment delivery timing",
      metrics: [{ label: "Segments", value: "Seasonal / Event + Promo" }, { label: "Value at risk", value: "$640K" }, { label: "Cost tradeoff", value: "Incremental route capacity" }],
      humanApprovalRequired: true,
      businessImpact: "Approved overflow capacity protects delivery timing for $640K in priority segment shipments.",
      recommendedAction: "Approve overflow route capacity and coordinate with transportation partners.",
      guardrailNote: "No incremental capacity committed without management and cost approval.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
]

// ─── STORE EXECUTION ─────────────────────────────────────────────────────────

export const storeActions: AIAction[] = [
  {
    id: "se-ai-1",
    title: "Linked display readiness to Promo / Merchant-Driven allocation",
    segment: "Promo / Merchant-Driven",
    sourceTab: "Store Execution",
    sourceTabId: "store-execution",
    detected: "Promo display completion below threshold in subset of stores",
    actionTaken: "Flagged stores where allocation should depend on display readiness confirmation",
    status: "watchlist",
    drawer: {
      title: "Linked display readiness to Promo / Merchant-Driven allocation",
      status: "watchlist",
      explanation: "AI detected that display readiness for Promo / Merchant-Driven SKU families is below threshold across a subset of stores. Allocating before display setup creates backroom overflow and wasted allocation capacity.",
      signals: ["Display readiness below threshold", "Promo / Merchant-Driven segment", "Allocation lock approaching", "Backroom overflow risk"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "store-execution",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Delay promo push pending display readiness confirmation",
      metrics: [{ label: "Segment", value: "Promo / Merchant-Driven" }, { label: "Value at risk", value: "$520K" }, { label: "Dependency", value: "Display readiness" }],
      humanApprovalRequired: true,
      businessImpact: "Early allocation without display readiness degrades promo sell-through and wastes allocation capacity.",
      recommendedAction: "Approve the display-readiness dependency rule below.",
      guardrailNote: "Watchlist — dependency flagged. No allocation delayed without approval.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "se-ai-2",
    title: "Detected backroom aging for Seasonal / Event SKUs",
    segment: "Seasonal / Event",
    sourceTab: "Store Execution",
    sourceTabId: "store-execution",
    detected: "Inventory aged over 48 hours in backroom across high-impact stores",
    actionTaken: "Created field action recommendation for backroom-to-shelf prioritization",
    status: "completed",
    drawer: {
      title: "Detected backroom aging for Seasonal / Event SKUs",
      status: "completed",
      explanation: "AI detected Seasonal / Event inventory sitting over 48 hours in backrooms at high-impact stores. Delayed backroom-to-shelf movement reduces effective shelf availability during the selling window.",
      signals: ["Seasonal / Event inventory aged >48 hours", "High-impact store subset", "Backroom aging threshold exceeded", "Selling window proximity"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "store-execution",
      segment: "Seasonal / Event",
      segmentStrategy: "Field action to prioritize backroom-to-shelf execution",
      metrics: [{ label: "Aging threshold", value: ">48 hours" }, { label: "Value at risk", value: "$1.8M" }, { label: "Segment", value: "Seasonal / Event" }],
      humanApprovalRequired: true,
      businessImpact: "Every hour of backroom aging during the selling window reduces effective sell-through — up to $1.8M at risk.",
      recommendedAction: "Approve field action for backroom aging below.",
      guardrailNote: "Field action recommendation is within guardrails. Store labor and DM sign-off required to execute.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "se-ai-3",
    title: "Identified phantom inventory risk for Constrained SKUs",
    segment: "Constrained / Exception",
    sourceTab: "Store Execution",
    sourceTabId: "store-execution",
    detected: "System inventory may not match physical shelf availability at select stores",
    actionTaken: "Created cycle count and verification recommendation for affected stores",
    status: "completed",
    drawer: {
      title: "Identified phantom inventory risk for Constrained SKUs",
      status: "completed",
      explanation: "AI detected signals suggesting that system-recorded inventory for Constrained / Exception SKUs may not match physical shelf availability at a subset of stores — creating phantom inventory that inflates availability metrics.",
      signals: ["System vs physical inventory discrepancy signals", "Constrained / Exception segment", "On-shelf availability anomaly", "Cycle count gap indicator"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "store-execution",
      segment: "Constrained / Exception",
      segmentStrategy: "Cycle count and inventory accuracy verification",
      metrics: [{ label: "Risk type", value: "Phantom inventory" }, { label: "Value at risk", value: "$780K" }, { label: "Verification needed", value: "Cycle count" }],
      humanApprovalRequired: true,
      businessImpact: "Phantom inventory causes over-reporting of shelf availability, masking real stockout risk for constrained SKUs.",
      recommendedAction: "Approve inventory accuracy verification and cycle count below.",
      guardrailNote: "Detection is autonomous. Cycle count and adjustment require store and inventory team sign-off.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
]

export const storeApprovals: ApprovalItem[] = [
  {
    id: "se-ap-1",
    title: "Approve display-readiness dependency rule",
    segment: "Promo / Merchant-Driven",
    recommendation: "Delay full promo push to stores without display readiness confirmation",
    whyApproval: "Field and merchandising agreement required — cannot automate store-level dependency",
    valueAtRisk: "$520K",
    owner: "Merchandising + Store Operations",
    status: "pending",
    drawer: {
      title: "Approve display-readiness dependency rule",
      status: "pending",
      explanation: "AI recommends creating a rule that delays full promo push to stores where display readiness is below threshold. This rule requires agreement from field and merchandising teams before it can be applied to allocation.",
      signals: ["Display readiness below threshold", "Promo / Merchant-Driven segment", "Field execution gap", "Merchandising sign-off needed"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }, { label: "Inventory & Allocation", id: "inventory" }],
      primarySourceTabId: "store-execution",
      segment: "Promo / Merchant-Driven",
      segmentStrategy: "Display-gated promo push allocation",
      metrics: [{ label: "Value at risk", value: "$520K" }, { label: "Rule type", value: "Display-readiness dependency" }, { label: "Teams affected", value: "Field + Merchandising" }],
      humanApprovalRequired: true,
      businessImpact: "Approved rule prevents wasted allocation to stores that cannot execute promo display — protecting $520K in promo sell-through.",
      recommendedAction: "Approve dependency rule and communicate to district managers.",
      guardrailNote: "No allocation held without explicit field and merchandising sign-off.",
      actionLabel: "Go to Inventory & Allocation",
      actionTabId: "inventory",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "se-ap-2",
    title: "Approve field action for backroom aging",
    segment: "Seasonal / Event",
    recommendation: "Prioritize backroom-to-shelf execution for high-impact stores within 48 hours",
    whyApproval: "Requires store labor reallocation and district manager action — not automatable",
    valueAtRisk: "$1.8M",
    owner: "Store Operations + District Managers",
    status: "pending",
    drawer: {
      title: "Approve field action for backroom aging",
      status: "pending",
      explanation: "AI has identified Seasonal / Event inventory sitting >48 hours in backrooms at high-impact stores. Field action requires district manager direction and store labor reallocation — neither of which can be automated.",
      signals: ["Backroom aging >48 hours", "Seasonal / Event segment", "High-impact stores identified", "Selling window approaching"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "store-execution",
      segment: "Seasonal / Event",
      segmentStrategy: "Backroom-to-shelf field execution prioritization",
      metrics: [{ label: "Value at risk", value: "$1.8M" }, { label: "Aging threshold", value: ">48 hours" }, { label: "Action scope", value: "High-impact stores" }],
      humanApprovalRequired: true,
      businessImpact: "Approving and executing field action recovers up to $1.8M in Seasonal / Event sell-through by clearing backroom aging before the window closes.",
      recommendedAction: "Approve field action and communicate priority to district managers.",
      guardrailNote: "No field directive issued without DM and store operations sign-off.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
  {
    id: "se-ap-3",
    title: "Approve inventory accuracy verification",
    segment: "Constrained / Exception",
    recommendation: "Create cycle count scope for stores with suspected phantom inventory",
    whyApproval: "Requires store execution and inventory adjustment — operational approval needed",
    valueAtRisk: "$780K",
    owner: "Store Operations + Inventory Control",
    status: "needs-approval",
    drawer: {
      title: "Approve inventory accuracy verification",
      status: "needs-approval",
      explanation: "AI has identified signals of phantom inventory for Constrained / Exception SKUs at a subset of stores. A cycle count is recommended to verify physical availability and correct system records. Operational approval required.",
      signals: ["System vs physical discrepancy signals", "Constrained / Exception segment", "Phantom inventory risk", "Cycle count scope identified"],
      sourceTabs: [{ label: "Store Execution", id: "store-execution" }],
      primarySourceTabId: "store-execution",
      segment: "Constrained / Exception",
      segmentStrategy: "Cycle count and system inventory correction",
      metrics: [{ label: "Value at risk", value: "$780K" }, { label: "Action", value: "Cycle count + adjustment" }, { label: "Teams", value: "Store Ops + Inventory Control" }],
      humanApprovalRequired: true,
      businessImpact: "Cycle count and correction ensures constrained SKU availability is accurately reported — preventing allocation decisions based on phantom stock.",
      recommendedAction: "Approve cycle count scope and schedule with store operations.",
      guardrailNote: "No inventory adjustment made without store and inventory control sign-off.",
      actionLabel: "Go to AI-Driven SKU Segmentation",
      actionTabId: "sku-segmentation",
      secondaryLabel: "Mark for review",
    },
  },
]
